//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CodeUserKind.
const (
	Agent CodeUserKind = "agent"
	Human CodeUserKind = "human"
)

// Valid indicates whether the value is a known member of the CodeUserKind enum.
func (e CodeUserKind) Valid() bool {
	switch e {
	case Agent:
		return true
	case Human:
		return true
	default:
		return false
	}
}

// Defines values for FileDiffCollapseReason.
const (
	Generated FileDiffCollapseReason = "generated"
	Large     FileDiffCollapseReason = "large"
	Lock      FileDiffCollapseReason = "lock"
)

// Valid indicates whether the value is a known member of the FileDiffCollapseReason enum.
func (e FileDiffCollapseReason) Valid() bool {
	switch e {
	case Generated:
		return true
	case Large:
		return true
	case Lock:
		return true
	default:
		return false
	}
}

// Defines values for FileDiffStatus.
const (
	Added    FileDiffStatus = "added"
	Copied   FileDiffStatus = "copied"
	Deleted  FileDiffStatus = "deleted"
	Modified FileDiffStatus = "modified"
	Renamed  FileDiffStatus = "renamed"
)

// Valid indicates whether the value is a known member of the FileDiffStatus enum.
func (e FileDiffStatus) Valid() bool {
	switch e {
	case Added:
		return true
	case Copied:
		return true
	case Deleted:
		return true
	case Modified:
		return true
	case Renamed:
		return true
	default:
		return false
	}
}

// Defines values for GitignoreTemplate.
const (
	Cpp       GitignoreTemplate = "cpp"
	Dotnet    GitignoreTemplate = "dotnet"
	Go        GitignoreTemplate = "go"
	Java      GitignoreTemplate = "java"
	Node      GitignoreTemplate = "node"
	Php       GitignoreTemplate = "php"
	Python    GitignoreTemplate = "python"
	Ruby      GitignoreTemplate = "ruby"
	Rust      GitignoreTemplate = "rust"
	Terraform GitignoreTemplate = "terraform"
)

// Valid indicates whether the value is a known member of the GitignoreTemplate enum.
func (e GitignoreTemplate) Valid() bool {
	switch e {
	case Cpp:
		return true
	case Dotnet:
		return true
	case Go:
		return true
	case Java:
		return true
	case Node:
		return true
	case Php:
		return true
	case Python:
		return true
	case Ruby:
		return true
	case Rust:
		return true
	case Terraform:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for LicenseTemplate.
const (
	Agpl30     LicenseTemplate = "agpl-3.0"
	Apache20   LicenseTemplate = "apache-2.0"
	Bsd2Clause LicenseTemplate = "bsd-2-clause"
	Bsd3Clause LicenseTemplate = "bsd-3-clause"
	Gpl30      LicenseTemplate = "gpl-3.0"
	Lgpl30     LicenseTemplate = "lgpl-3.0"
	Mit        LicenseTemplate = "mit"
	Mpl20      LicenseTemplate = "mpl-2.0"
	Unlicense  LicenseTemplate = "unlicense"
)

// Valid indicates whether the value is a known member of the LicenseTemplate enum.
func (e LicenseTemplate) Valid() bool {
	switch e {
	case Agpl30:
		return true
	case Apache20:
		return true
	case Bsd2Clause:
		return true
	case Bsd3Clause:
		return true
	case Gpl30:
		return true
	case Lgpl30:
		return true
	case Mit:
		return true
	case Mpl20:
		return true
	case Unlicense:
		return true
	default:
		return false
	}
}

// Defines values for OwnerType.
const (
	Organization OwnerType = "organization"
	User         OwnerType = "user"
)

// Valid indicates whether the value is a known member of the OwnerType enum.
func (e OwnerType) Valid() bool {
	switch e {
	case Organization:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for RepoVisibility.
const (
	Internal RepoVisibility = "internal"
	Private  RepoVisibility = "private"
)

// Valid indicates whether the value is a known member of the RepoVisibility enum.
func (e RepoVisibility) Valid() bool {
	switch e {
	case Internal:
		return true
	case Private:
		return true
	default:
		return false
	}
}

// Defines values for TreeEntryType.
const (
	Dir       TreeEntryType = "dir"
	File      TreeEntryType = "file"
	Submodule TreeEntryType = "submodule"
	Symlink   TreeEntryType = "symlink"
)

// Valid indicates whether the value is a known member of the TreeEntryType enum.
func (e TreeEntryType) Valid() bool {
	switch e {
	case Dir:
		return true
	case File:
		return true
	case Submodule:
		return true
	case Symlink:
		return true
	default:
		return false
	}
}

// Blame defines model for Blame.
type Blame struct {
	Path   string       `json:"path"`
	Ranges []BlameRange `json:"ranges"`
	Ref    string       `json:"ref"`
}

// BlameRange defines model for BlameRange.
type BlameRange struct {
	Commit    CommitSummary `json:"commit"`
	EndLine   int           `json:"endLine"`
	StartLine int           `json:"startLine"`
}

// Branch defines model for Branch.
type Branch struct {
	Commit    CommitSummary `json:"commit"`
	IsDefault bool          `json:"isDefault"`
	Name      string        `json:"name"`

	// Protected Protezione del branch principale (R9). Per il servizio git e' sempre false, la imposta core.
	Protected bool `json:"protected"`
}

// BranchList defines model for BranchList.
type BranchList struct {
	Items []Branch `json:"items"`
	Total int      `json:"total"`
}

// CodeUser Utente GitStack che corrisponde all'email di un commit (confronto senza distinguere maiuscole con l'email di identity). `kind` da' il badge umano/agente.
type CodeUser struct {
	AvatarUrl *string            `json:"avatarUrl"`
	Id        openapi_types.UUID `json:"id"`
	Kind      CodeUserKind       `json:"kind"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// CodeUserKind defines model for CodeUser.Kind.
type CodeUserKind string

// CommitDetail defines model for CommitDetail.
type CommitDetail struct {
	Additions int           `json:"additions"`
	Commit    CommitSummary `json:"commit"`
	Deletions int           `json:"deletions"`
	Files     []FileDiff    `json:"files"`

	// FilesChanged Numero reale di file toccati, anche oltre i 300 elencati.
	FilesChanged int `json:"filesChanged"`

	// IgnoreWhitespace Il diff e' stato calcolato ignorando gli spazi (`git diff -w`); i file che cambiano solo negli spazi non compaiono.
	IgnoreWhitespace *bool `json:"ignoreWhitespace,omitempty"`

	// ListOnly B6: oltre 300 file o 20 000 righe cambiate la risposta porta solo l'elenco dei file con righe aggiunte e tolte, senza `patch`.
	ListOnly *bool `json:"listOnly,omitempty"`

	// Tags Tag che puntano al commit (anche annotati), in ordine alfabetico.
	Tags *[]string `json:"tags,omitempty"`

	// Truncated True se i file sono oltre 300 o le righe di diff oltre 20 000 in totale.
	Truncated bool `json:"truncated"`
}

// CommitList defines model for CommitList.
type CommitList struct {
	// HasMore Non c'e' un totale, contarlo costa un giro completo della storia.
	HasMore bool            `json:"hasMore"`
	Items   []CommitSummary `json:"items"`
	Page    int             `json:"page"`
	PerPage int             `json:"perPage"`
}

// CommitPerson Autore o committer dichiarato nel commit. Non e' una prova d'identita': chiunque puo' scrivere un nome e un'email qualsiasi in un commit. `user` e' null se nessun utente GitStack ha quell'email (e sempre assente nelle risposte del servizio git, che non conosce gli utenti).
type CommitPerson struct {
	Date  time.Time `json:"date"`
	Email string    `json:"email"`
	Name  string    `json:"name"`
	User  *CodeUser `json:"user,omitempty"`
}

// CommitSummary defines model for CommitSummary.
type CommitSummary struct {
	// Author Autore o committer dichiarato nel commit. Non e' una prova d'identita': chiunque puo' scrivere un nome e un'email qualsiasi in un commit. `user` e' null se nessun utente GitStack ha quell'email (e sempre assente nelle risposte del servizio git, che non conosce gli utenti).
	Author CommitPerson `json:"author"`

	// Committer Autore o committer dichiarato nel commit. Non e' una prova d'identita': chiunque puo' scrivere un nome e un'email qualsiasi in un commit. `user` e' null se nessun utente GitStack ha quell'email (e sempre assente nelle risposte del servizio git, che non conosce gli utenti).
	Committer CommitPerson `json:"committer"`

	// Message Messaggio completo (omesso nell'ultimo commit di una voce d'albero).
	Message *string  `json:"message,omitempty"`
	Parents []string `json:"parents"`
	Sha     string   `json:"sha"`

	// Subject Prima riga del messaggio.
	Subject string `json:"subject"`
}

// CreateRepositoryInput defines model for CreateRepositoryInput.
type CreateRepositoryInput struct {
	Description *string `json:"description,omitempty"`

	// GitignoreTemplate Modello di `.gitignore` per il contenuto iniziale (R5).
	GitignoreTemplate *GitignoreTemplate `json:"gitignoreTemplate,omitempty"`

	// LicenseTemplate Modello di licenza per il contenuto iniziale (R5).
	LicenseTemplate *LicenseTemplate `json:"licenseTemplate,omitempty"`

	// Name Nome di un repo (R11): minuscole, cifre, `-`, `_`, `.`; 1-100 caratteri; non inizia con `.`; non finisce con `.git` (regola applicata dal servizio, non esprimibile nel pattern). Le maiuscole sono rifiutate. Unico per owner.
	//
	//
	// Example: my-app
	Name RepoName `json:"name"`

	// Owner Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Owner Name `json:"owner"`

	// Readme Crea un `README.md` iniziale (R5).
	Readme *bool `json:"readme,omitempty"`

	// Visibility Visibilita' (P7): `private` (solo chi ha un grant) o `internal` (tutti gli utenti dell'installazione). Nessun accesso anonimo.
	Visibility *RepoVisibility `json:"visibility,omitempty"`
}

// CreateResourceInput defines model for CreateResourceInput.
type CreateResourceInput struct {
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	Name       string                  `json:"name"`

	// Type Example: repo
	Type string `json:"type"`
}

// DeletedRepository defines model for DeletedRepository.
type DeletedRepository struct {
	DeletedAt time.Time          `json:"deletedAt"`
	Id        openapi_types.UUID `json:"id"`

	// Name Nome di un repo (R11): minuscole, cifre, `-`, `_`, `.`; 1-100 caratteri; non inizia con `.`; non finisce con `.git` (regola applicata dal servizio, non esprimibile nel pattern). Le maiuscole sono rifiutate. Unico per owner.
	//
	//
	// Example: my-app
	Name  RepoName  `json:"name"`
	Owner RepoOwner `json:"owner"`

	// PurgeAt Dopo questo istante il repo e' cancellato definitivamente (7 giorni, R2).
	PurgeAt time.Time `json:"purgeAt"`
}

// DeletedRepositoryList defines model for DeletedRepositoryList.
type DeletedRepositoryList struct {
	Items []DeletedRepository `json:"items"`
}

// Error Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Error struct {
	Error struct {
		// Code Codice stabile leggibile da macchina (es. `not_found`).
		//
		// Example: not_found
		Code string `json:"code"`

		// Details Dettagli opzionali specifici dell'errore.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Messaggio leggibile da persone, non contrattuale.
		Message string `json:"message"`
	} `json:"error"`
}

// FileContent defines model for FileContent.
type FileContent struct {
	Binary bool `json:"binary"`

	// Content Testo UTF-8; assente se `binary` (usare `raw`).
	Content    *string       `json:"content,omitempty"`
	LastCommit CommitSummary `json:"lastCommit"`
	Name       string        `json:"name"`
	Path       string        `json:"path"`
	Ref        string        `json:"ref"`

	// Sha Sha del blob.
	Sha string `json:"sha"`

	// Size Dimensione reale in byte, anche se troncato.
	Size int64 `json:"size"`

	// Truncated True se `size` supera 1 048 576 byte e `content` ne porta solo il primo megabyte.
	Truncated bool `json:"truncated"`
}

// FileDiff defines model for FileDiff.
type FileDiff struct {
	Additions int  `json:"additions"`
	Binary    bool `json:"binary"`

	// CollapseReason Perche' e' chiuso: `large` (piu' di 500 righe cambiate, aggiunte piu' tolte), `lock` (file di lock: package-lock.json, pnpm-lock.yaml, yarn.lock, go.sum, Cargo.lock, ...) o `generated` (file generato o minificato: *.min.js, *.min.css, *.pb.go, ...). Elenco completo nel README del servizio git; lock e generated vincono su large.
	CollapseReason *FileDiffCollapseReason `json:"collapseReason,omitempty"`

	// Collapsed B6: il file e' «chiuso di default» nella UI. Il patch c'e' comunque, se non e' stato omesso per i limiti.
	Collapsed *bool `json:"collapsed,omitempty"`
	Deletions int   `json:"deletions"`

	// OldPath Percorso precedente, per rinomine e copie.
	OldPath *string `json:"oldPath,omitempty"`

	// Patch Diff unificato (hunk), assente per i binari.
	Patch  *string        `json:"patch,omitempty"`
	Path   string         `json:"path"`
	Status FileDiffStatus `json:"status"`

	// Truncated True se il patch supera 1 MB o il limite totale di 20 000 righe e' gia' esaurito; `patch` e' parziale o assente.
	Truncated bool `json:"truncated"`
}

// FileDiffCollapseReason Perche' e' chiuso: `large` (piu' di 500 righe cambiate, aggiunte piu' tolte), `lock` (file di lock: package-lock.json, pnpm-lock.yaml, yarn.lock, go.sum, Cargo.lock, ...) o `generated` (file generato o minificato: *.min.js, *.min.css, *.pb.go, ...). Elenco completo nel README del servizio git; lock e generated vincono su large.
type FileDiffCollapseReason string

// FileDiffStatus defines model for FileDiff.Status.
type FileDiffStatus string

// GitignoreTemplate Modello di `.gitignore` per il contenuto iniziale (R5).
type GitignoreTemplate string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Versione del contratto API in esecuzione (`info.version`).
	Version string `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LanguageShare defines model for LanguageShare.
type LanguageShare struct {
	Bytes   int64   `json:"bytes"`
	Name    string  `json:"name"`
	Percent float32 `json:"percent"`
}

// Languages defines model for Languages.
type Languages struct {
	Languages  []LanguageShare `json:"languages"`
	TotalBytes int64           `json:"totalBytes"`
}

// LicenseTemplate Modello di licenza per il contenuto iniziale (R5).
type LicenseTemplate string

// Name Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type Name = string

// OwnerType defines model for OwnerType.
type OwnerType string

// RepoCloneUrls Indirizzi di clone dell'installazione (R1, R7). L'indirizzo SSH e' sempre quello completo `ssh://git@<host>:<porta>/<owner>/<repo>.git`.
type RepoCloneUrls struct {
	// Https Example: https://git.example.com/alice/my-app.git
	Https string `json:"https"`

	// Ssh Example: ssh://git@git.example.com:2222/alice/my-app.git
	Ssh string `json:"ssh"`

	// SshShort Forma corta `git@<host>:<owner>/<repo>.git` (R7): presente solo quando la porta SSH dell'installazione e' 22.
	//
	//
	// Example: git@git.example.com:alice/my-app.git
	SshShort *string `json:"sshShort,omitempty"`
}

// RepoName Nome di un repo (R11): minuscole, cifre, `-`, `_`, `.`; 1-100 caratteri; non inizia con `.`; non finisce con `.git` (regola applicata dal servizio, non esprimibile nel pattern). Le maiuscole sono rifiutate. Unico per owner.
//
// Example: my-app
type RepoName = string

// RepoOwner defines model for RepoOwner.
type RepoOwner struct {
	// Name Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Name Name      `json:"name"`
	Type OwnerType `json:"type"`
}

// RepoVisibility Visibilita' (P7): `private` (solo chi ha un grant) o `internal` (tutti gli utenti dell'installazione). Nessun accesso anonimo.
type RepoVisibility string

// Repository defines model for Repository.
type Repository struct {
	Archived   bool       `json:"archived"`
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`

	// CloneUrls Indirizzi di clone dell'installazione (R1, R7). L'indirizzo SSH e' sempre quello completo `ssh://git@<host>:<porta>/<owner>/<repo>.git`.
	CloneUrls RepoCloneUrls `json:"cloneUrls"`
	CreatedAt *time.Time    `json:"createdAt,omitempty"`

	// DefaultBranch Example: main
	DefaultBranch string `json:"defaultBranch"`
	Description   string `json:"description"`

	// Empty Il repo non ha ancora nessun commit.
	Empty bool `json:"empty"`

	// FullName `owner/name`.
	//
	// Example: alice/my-app
	FullName string `json:"fullName"`

	// Id Id della risorsa (`type=repo`) in core.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Name Nome di un repo (R11): minuscole, cifre, `-`, `_`, `.`; 1-100 caratteri; non inizia con `.`; non finisce con `.git` (regola applicata dal servizio, non esprimibile nel pattern). Le maiuscole sono rifiutate. Unico per owner.
	//
	//
	// Example: my-app
	Name  RepoName  `json:"name"`
	Owner RepoOwner `json:"owner"`

	// ProtectDefaultBranch Force-push ed eliminazione del branch principale rifiutati (R9).
	ProtectDefaultBranch bool       `json:"protectDefaultBranch"`
	UpdatedAt            *time.Time `json:"updatedAt,omitempty"`

	// Visibility Visibilita' (P7): `private` (solo chi ha un grant) o `internal` (tutti gli utenti dell'installazione). Nessun accesso anonimo.
	Visibility RepoVisibility `json:"visibility"`
}

// RepositoryList defines model for RepositoryList.
type RepositoryList struct {
	Items   []Repository `json:"items"`
	Page    int          `json:"page"`
	PerPage int          `json:"perPage"`
	Total   int          `json:"total"`
}

// Resource Risorsa generica (D15): oggi usata dalla prova end-to-end, in futuro anche per repository, applicazioni e database, senza cambiare forma.
type Resource struct {
	// Attributes Attributi specifici del tipo di risorsa, a forma libera.
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	CreatedAt  *time.Time              `json:"createdAt,omitempty"`
	Id         *openapi_types.UUID     `json:"id,omitempty"`
	Name       string                  `json:"name"`

	// Type Tipo di risorsa, aperto: non un enum fisso (D15).
	//
	// Example: repo
	Type      string     `json:"type"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ResourceList defines model for ResourceList.
type ResourceList struct {
	Items   []Resource `json:"items"`
	Page    int        `json:"page"`
	PerPage int        `json:"perPage"`
	Total   int        `json:"total"`
}

// Tag defines model for Tag.
type Tag struct {
	Annotated bool          `json:"annotated"`
	Commit    CommitSummary `json:"commit"`

	// Message Messaggio del tag annotato.
	Message  *string    `json:"message,omitempty"`
	Name     string     `json:"name"`
	TaggedAt *time.Time `json:"taggedAt,omitempty"`
}

// TagList defines model for TagList.
type TagList struct {
	Items []Tag `json:"items"`
	Total int   `json:"total"`
}

// Tree defines model for Tree.
type Tree struct {
	CommitSha string      `json:"commitSha"`
	Entries   []TreeEntry `json:"entries"`
	Path      string      `json:"path"`

	// Ref Il `ref` risolto (il branch principale se non indicato).
	Ref string `json:"ref"`

	// Truncated True se la cartella ha piu' di 1 000 voci e queste sono le prime 1 000.
	Truncated bool `json:"truncated"`
}

// TreeEntry defines model for TreeEntry.
type TreeEntry struct {
	LastCommit CommitSummary `json:"lastCommit"`

	// Mode Modo Git in ottale, es. `100644`.
	Mode string `json:"mode"`
	Name string `json:"name"`
	Path string `json:"path"`

	// Size Byte, solo per i file.
	Size *int64        `json:"size,omitempty"`
	Type TreeEntryType `json:"type"`
}

// TreeEntryType defines model for TreeEntry.Type.
type TreeEntryType string

// UpdateRepositoryInput defines model for UpdateRepositoryInput.
type UpdateRepositoryInput struct {
	Archived             *bool   `json:"archived,omitempty"`
	DefaultBranch        *string `json:"defaultBranch,omitempty"`
	Description          *string `json:"description,omitempty"`
	ProtectDefaultBranch *bool   `json:"protectDefaultBranch,omitempty"`

	// Visibility Visibilita' (P7): `private` (solo chi ha un grant) o `internal` (tutti gli utenti dell'installazione). Nessun accesso anonimo.
	Visibility *RepoVisibility `json:"visibility,omitempty"`
}

// UpdateResourceInput defines model for UpdateResourceInput.
type UpdateResourceInput struct {
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	Name       *string                 `json:"name,omitempty"`
}

// CommitAuthorFilter defines model for CommitAuthorFilter.
type CommitAuthorFilter = string

// CommitPageParam defines model for CommitPageParam.
type CommitPageParam = int

// CommitPerPageParam defines model for CommitPerPageParam.
type CommitPerPageParam = int

// CommitShaParam defines model for CommitShaParam.
type CommitShaParam = string

// FilePathParam defines model for FilePathParam.
type FilePathParam = string

// GitRepoIdParam defines model for GitRepoIdParam.
type GitRepoIdParam = openapi_types.UUID

// GrantIdParam defines model for GrantIdParam.
type GrantIdParam = openapi_types.UUID

// OidcProviderParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OidcProviderParam = Name

// OrgParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OrgParam = Name

// PageParam defines model for PageParam.
type PageParam = int

// PathParam defines model for PathParam.
type PathParam = string

// PerPageParam defines model for PerPageParam.
type PerPageParam = int

// RefParam defines model for RefParam.
type RefParam = string

// RepoNameParam Nome di un repo (R11): minuscole, cifre, `-`, `_`, `.`; 1-100 caratteri; non inizia con `.`; non finisce con `.git` (regola applicata dal servizio, non esprimibile nel pattern). Le maiuscole sono rifiutate. Unico per owner.
//
// Example: my-app
type RepoNameParam = RepoName

// RepoOwnerFilter Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type RepoOwnerFilter = Name

// RepoOwnerParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type RepoOwnerParam = Name

// ResourceIdParam defines model for ResourceIdParam.
type ResourceIdParam = openapi_types.UUID

// ResourceTypeFilter defines model for ResourceTypeFilter.
type ResourceTypeFilter = string

// SshKeyIdParam defines model for SshKeyIdParam.
type SshKeyIdParam = openapi_types.UUID

// TeamParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type TeamParam = Name

// TokenIdParam defines model for TokenIdParam.
type TokenIdParam = openapi_types.UUID

// UsernameParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type UsernameParam = Name

// BadRequest Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type BadRequest = Error

// Conflict Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Conflict = Error

// Forbidden Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Forbidden = Error

// NotFound Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type NotFound = Error

// Unauthorized Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Unauthorized = Error

// UnexpectedError Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type UnexpectedError = Error

// ListRepositoriesParams defines parameters for ListRepositories.
type ListRepositoriesParams struct {
	// Owner Filtra per nome dell'utente o dell'organizzazione proprietaria.
	Owner   *RepoOwnerFilter `form:"owner,omitempty" json:"owner,omitempty"`
	Page    *PageParam       `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageParam    `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListDeletedRepositoriesParams defines parameters for ListDeletedRepositories.
type ListDeletedRepositoriesParams struct {
	// Owner Filtra per nome dell'utente o dell'organizzazione proprietaria.
	Owner *RepoOwnerFilter `form:"owner,omitempty" json:"owner,omitempty"`
}

// GetRepositoryArchiveParams defines parameters for GetRepositoryArchive.
type GetRepositoryArchiveParams struct {
	// Ref Branch, tag o sha (completo o prefisso di almeno 7 caratteri). Se manca vale il branch principale del repo (R4). Un nome non valido (vuoto, con `..`, spazi, caratteri di controllo o oltre 255 caratteri) risponde 400 `invalid_ref`; uno valido ma inesistente 404 `ref_not_found`. Se un nome e' sia branch sia tag vince il branch.
	Ref *RefParam `form:"ref,omitempty" json:"ref,omitempty"`
}

// GetRepositoryBlameParams defines parameters for GetRepositoryBlame.
type GetRepositoryBlameParams struct {
	// Ref Branch, tag o sha (completo o prefisso di almeno 7 caratteri). Se manca vale il branch principale del repo (R4). Un nome non valido (vuoto, con `..`, spazi, caratteri di controllo o oltre 255 caratteri) risponde 400 `invalid_ref`; uno valido ma inesistente 404 `ref_not_found`. Se un nome e' sia branch sia tag vince il branch.
	Ref *RefParam `form:"ref,omitempty" json:"ref,omitempty"`

	// Path Percorso del file (stesse regole di `PathParam`, non vuoto).
	Path FilePathParam `form:"path" json:"path"`
}

// GetRepositoryCommitsParams defines parameters for GetRepositoryCommits.
type GetRepositoryCommitsParams struct {
	// Ref Branch, tag o sha (completo o prefisso di almeno 7 caratteri). Se manca vale il branch principale del repo (R4). Un nome non valido (vuoto, con `..`, spazi, caratteri di controllo o oltre 255 caratteri) risponde 400 `invalid_ref`; uno valido ma inesistente 404 `ref_not_found`. Se un nome e' sia branch sia tag vince il branch.
	Ref *RefParam `form:"ref,omitempty" json:"ref,omitempty"`

	// Author Solo i commit il cui autore ha questo nome o email (senza distinguere maiuscole).
	Author *CommitAuthorFilter `form:"author,omitempty" json:"author,omitempty"`

	// Path Percorso relativo alla radice del repo, con `/` come separatore, senza `/` iniziale e senza segmenti `.` o `..` (400 `invalid_path`). Assente o vuoto: la radice.
	Path *PathParam       `form:"path,omitempty" json:"path,omitempty"`
	Page *CommitPageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Commit per pagina (default 30, massimo 100).
	PerPage *CommitPerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// GetRepositoryFileParams defines parameters for GetRepositoryFile.
type GetRepositoryFileParams struct {
	// Ref Branch, tag o sha (completo o prefisso di almeno 7 caratteri). Se manca vale il branch principale del repo (R4). Un nome non valido (vuoto, con `..`, spazi, caratteri di controllo o oltre 255 caratteri) risponde 400 `invalid_ref`; uno valido ma inesistente 404 `ref_not_found`. Se un nome e' sia branch sia tag vince il branch.
	Ref *RefParam `form:"ref,omitempty" json:"ref,omitempty"`

	// Path Percorso del file (stesse regole di `PathParam`, non vuoto).
	Path FilePathParam `form:"path" json:"path"`
}

// GetRepositoryLanguagesParams defines parameters for GetRepositoryLanguages.
type GetRepositoryLanguagesParams struct {
	// Ref Branch, tag o sha (completo o prefisso di almeno 7 caratteri). Se manca vale il branch principale del repo (R4). Un nome non valido (vuoto, con `..`, spazi, caratteri di controllo o oltre 255 caratteri) risponde 400 `invalid_ref`; uno valido ma inesistente 404 `ref_not_found`. Se un nome e' sia branch sia tag vince il branch.
	Ref *RefParam `form:"ref,omitempty" json:"ref,omitempty"`
}

// GetRepositoryRawParams defines parameters for GetRepositoryRaw.
type GetRepositoryRawParams struct {
	// Ref Branch, tag o sha (completo o prefisso di almeno 7 caratteri). Se manca vale il branch principale del repo (R4). Un nome non valido (vuoto, con `..`, spazi, caratteri di controllo o oltre 255 caratteri) risponde 400 `invalid_ref`; uno valido ma inesistente 404 `ref_not_found`. Se un nome e' sia branch sia tag vince il branch.
	Ref *RefParam `form:"ref,omitempty" json:"ref,omitempty"`

	// Path Percorso del file (stesse regole di `PathParam`, non vuoto).
	Path FilePathParam `form:"path" json:"path"`
}

// GetRepositoryReadmeParams defines parameters for GetRepositoryReadme.
type GetRepositoryReadmeParams struct {
	// Ref Branch, tag o sha (completo o prefisso di almeno 7 caratteri). Se manca vale il branch principale del repo (R4). Un nome non valido (vuoto, con `..`, spazi, caratteri di controllo o oltre 255 caratteri) risponde 400 `invalid_ref`; uno valido ma inesistente 404 `ref_not_found`. Se un nome e' sia branch sia tag vince il branch.
	Ref *RefParam `form:"ref,omitempty" json:"ref,omitempty"`

	// Path Percorso relativo alla radice del repo, con `/` come separatore, senza `/` iniziale e senza segmenti `.` o `..` (400 `invalid_path`). Assente o vuoto: la radice.
	Path *PathParam `form:"path,omitempty" json:"path,omitempty"`
}

// GetRepositoryTreeParams defines parameters for GetRepositoryTree.
type GetRepositoryTreeParams struct {
	// Ref Branch, tag o sha (completo o prefisso di almeno 7 caratteri). Se manca vale il branch principale del repo (R4). Un nome non valido (vuoto, con `..`, spazi, caratteri di controllo o oltre 255 caratteri) risponde 400 `invalid_ref`; uno valido ma inesistente 404 `ref_not_found`. Se un nome e' sia branch sia tag vince il branch.
	Ref *RefParam `form:"ref,omitempty" json:"ref,omitempty"`

	// Path Percorso relativo alla radice del repo, con `/` come separatore, senza `/` iniziale e senza segmenti `.` o `..` (400 `invalid_path`). Assente o vuoto: la radice.
	Path *PathParam `form:"path,omitempty" json:"path,omitempty"`
}

// ListResourcesParams defines parameters for ListResources.
type ListResourcesParams struct {
	// Type Filtra per tipo di risorsa (es. `repo`).
	Type    *ResourceTypeFilter `form:"type,omitempty" json:"type,omitempty"`
	Page    *PageParam          `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageParam       `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// CreateRepositoryJSONRequestBody defines body for CreateRepository for application/json ContentType.
type CreateRepositoryJSONRequestBody = CreateRepositoryInput

// UpdateRepositoryJSONRequestBody defines body for UpdateRepository for application/json ContentType.
type UpdateRepositoryJSONRequestBody = UpdateRepositoryInput

// CreateResourceJSONRequestBody defines body for CreateResource for application/json ContentType.
type CreateResourceJSONRequestBody = CreateResourceInput

// UpdateResourceJSONRequestBody defines body for UpdateResource for application/json ContentType.
type UpdateResourceJSONRequestBody = UpdateResourceInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Stato del servizio
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ListRepositories Elenca i repo leggibili dall'utente
	// (GET /repos)
	ListRepositories(w http.ResponseWriter, r *http.Request, params ListRepositoriesParams)
	// CreateRepository Crea un repo
	// (POST /repos)
	CreateRepository(w http.ResponseWriter, r *http.Request)
	// ListDeletedRepositories Elenca i repo eliminati e ancora ripristinabili
	// (GET /repos/deleted)
	ListDeletedRepositories(w http.ResponseWriter, r *http.Request, params ListDeletedRepositoriesParams)
	// RestoreRepository Ripristina un repo eliminato
	// (POST /repos/deleted/{repoId}/restore)
	RestoreRepository(w http.ResponseWriter, r *http.Request, repoId openapi_types.UUID)
	// DeleteRepository Elimina un repo (recuperabile per 7 giorni)
	// (DELETE /repos/{owner}/{repo})
	DeleteRepository(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam)
	// GetRepository Legge un repo per owner/nome
	// (GET /repos/{owner}/{repo})
	GetRepository(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam)
	// UpdateRepository Modifica le impostazioni di un repo
	// (PATCH /repos/{owner}/{repo})
	UpdateRepository(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam)
	// GetRepositoryArchive Archivio ZIP di un ref (streaming)
	// (GET /repos/{owner}/{repo}/archive)
	GetRepositoryArchive(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam, params GetRepositoryArchiveParams)
	// GetRepositoryBlame Blame di un file
	// (GET /repos/{owner}/{repo}/blame)
	GetRepositoryBlame(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam, params GetRepositoryBlameParams)
	// GetRepositoryBranches Branch del repo, con conteggi
	// (GET /repos/{owner}/{repo}/branches)
	GetRepositoryBranches(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam)
	// GetRepositoryCommits Storico dei commit, paginato
	// (GET /repos/{owner}/{repo}/commits)
	GetRepositoryCommits(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam, params GetRepositoryCommitsParams)
	// GetRepositoryCommit Dettaglio di un commit con diff per file
	// (GET /repos/{owner}/{repo}/commits/{sha})
	GetRepositoryCommit(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam, sha CommitShaParam)
	// GetRepositoryFile Contenuto di un file
	// (GET /repos/{owner}/{repo}/contents)
	GetRepositoryFile(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam, params GetRepositoryFileParams)
	// GetRepositoryLanguages Lingue del repo
	// (GET /repos/{owner}/{repo}/languages)
	GetRepositoryLanguages(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam, params GetRepositoryLanguagesParams)
	// GetRepositoryRaw Contenuto grezzo di un file (streaming)
	// (GET /repos/{owner}/{repo}/raw)
	GetRepositoryRaw(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam, params GetRepositoryRawParams)
	// GetRepositoryReadme README di una cartella
	// (GET /repos/{owner}/{repo}/readme)
	GetRepositoryReadme(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam, params GetRepositoryReadmeParams)
	// GetRepositoryTags Tag del repo, con conteggi
	// (GET /repos/{owner}/{repo}/tags)
	GetRepositoryTags(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam)
	// GetRepositoryTree Albero di una cartella con l'ultimo commit per voce
	// (GET /repos/{owner}/{repo}/tree)
	GetRepositoryTree(w http.ResponseWriter, r *http.Request, owner RepoOwnerParam, repo RepoNameParam, params GetRepositoryTreeParams)
	// ListResources Elenca le risorse
	// (GET /resources)
	ListResources(w http.ResponseWriter, r *http.Request, params ListResourcesParams)
	// CreateResource Crea una risorsa
	// (POST /resources)
	CreateResource(w http.ResponseWriter, r *http.Request)
	// DeleteResource Elimina una risorsa
	// (DELETE /resources/{resourceId})
	DeleteResource(w http.ResponseWriter, r *http.Request, resourceId ResourceIdParam)
	// GetResource Legge una risorsa
	// (GET /resources/{resourceId})
	GetResource(w http.ResponseWriter, r *http.Request, resourceId ResourceIdParam)
	// UpdateResource Aggiorna una risorsa
	// (PATCH /resources/{resourceId})
	UpdateResource(w http.ResponseWriter, r *http.Request, resourceId ResourceIdParam)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListRepositories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRepositoriesParams

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepositories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRepository operation middleware
func (siw *ServerInterfaceWrapper) CreateRepository(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRepository(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeletedRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListDeletedRepositories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDeletedRepositoriesParams

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeletedRepositories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreRepository operation middleware
func (siw *ServerInterfaceWrapper) RestoreRepository(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "repoId" -------------
	var repoId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "repoId", r.PathValue("repoId"), &repoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repoId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreRepository(w, r, repoId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRepository operation middleware
func (siw *ServerInterfaceWrapper) DeleteRepository(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRepository(w, r, owner, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepository operation middleware
func (siw *ServerInterfaceWrapper) GetRepository(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepository(w, r, owner, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRepository operation middleware
func (siw *ServerInterfaceWrapper) UpdateRepository(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRepository(w, r, owner, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryArchive operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryArchive(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRepositoryArchiveParams

	// ------------- Optional query parameter "ref" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ref", r.URL.Query(), &params.Ref, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ref"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ref", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryArchive(w, r, owner, repo, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryBlame operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryBlame(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRepositoryBlameParams

	// ------------- Optional query parameter "ref" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ref", r.URL.Query(), &params.Ref, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ref"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ref", Err: err})
		}
		return
	}

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryBlame(w, r, owner, repo, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryBranches operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryBranches(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryBranches(w, r, owner, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryCommits operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryCommits(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRepositoryCommitsParams

	// ------------- Optional query parameter "ref" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ref", r.URL.Query(), &params.Ref, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ref"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ref", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "author" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "author", r.URL.Query(), &params.Author, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "author"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryCommits(w, r, owner, repo, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryCommit operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryCommit(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// ------------- Path parameter "sha" -------------
	var sha CommitShaParam

	err = runtime.BindStyledParameterWithOptions("simple", "sha", r.PathValue("sha"), &sha, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sha", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryCommit(w, r, owner, repo, sha)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryFile operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryFile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRepositoryFileParams

	// ------------- Optional query parameter "ref" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ref", r.URL.Query(), &params.Ref, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ref"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ref", Err: err})
		}
		return
	}

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryFile(w, r, owner, repo, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryLanguages operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryLanguages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRepositoryLanguagesParams

	// ------------- Optional query parameter "ref" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ref", r.URL.Query(), &params.Ref, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ref"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ref", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryLanguages(w, r, owner, repo, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryRaw operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryRaw(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRepositoryRawParams

	// ------------- Optional query parameter "ref" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ref", r.URL.Query(), &params.Ref, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ref"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ref", Err: err})
		}
		return
	}

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryRaw(w, r, owner, repo, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryReadme operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryReadme(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRepositoryReadmeParams

	// ------------- Optional query parameter "ref" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ref", r.URL.Query(), &params.Ref, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ref"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ref", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryReadme(w, r, owner, repo, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryTags operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryTags(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryTags(w, r, owner, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoryTree operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoryTree(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "owner" -------------
	var owner RepoOwnerParam

	err = runtime.BindStyledParameterWithOptions("simple", "owner", r.PathValue("owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo RepoNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "repo", r.PathValue("repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRepositoryTreeParams

	// ------------- Optional query parameter "ref" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ref", r.URL.Query(), &params.Ref, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ref"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ref", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoryTree(w, r, owner, repo, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListResources operation middleware
func (siw *ServerInterfaceWrapper) ListResources(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListResourcesParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListResources(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateResource operation middleware
func (siw *ServerInterfaceWrapper) CreateResource(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateResource(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteResource operation middleware
func (siw *ServerInterfaceWrapper) DeleteResource(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId ResourceIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", r.PathValue("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteResource(w, r, resourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetResource operation middleware
func (siw *ServerInterfaceWrapper) GetResource(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId ResourceIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", r.PathValue("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetResource(w, r, resourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateResource operation middleware
func (siw *ServerInterfaceWrapper) UpdateResource(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId ResourceIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", r.PathValue("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateResource(w, r, resourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/resources", wrapper.ListResources)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/resources", wrapper.CreateResource)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/resources/{resourceId}", wrapper.DeleteResource)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/resources/{resourceId}", wrapper.GetResource)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/resources/{resourceId}", wrapper.UpdateResource)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos", wrapper.ListRepositories)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/repos", wrapper.CreateRepository)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/deleted", wrapper.ListDeletedRepositories)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/repos/deleted/{repoId}/restore", wrapper.RestoreRepository)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/repos/{owner}/{repo}", wrapper.DeleteRepository)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}", wrapper.GetRepository)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/repos/{owner}/{repo}", wrapper.UpdateRepository)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/tree", wrapper.GetRepositoryTree)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/contents", wrapper.GetRepositoryFile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/raw", wrapper.GetRepositoryRaw)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/branches", wrapper.GetRepositoryBranches)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/tags", wrapper.GetRepositoryTags)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/commits", wrapper.GetRepositoryCommits)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/commits/{sha}", wrapper.GetRepositoryCommit)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/blame", wrapper.GetRepositoryBlame)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/archive", wrapper.GetRepositoryArchive)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/languages", wrapper.GetRepositoryLanguages)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{owner}/{repo}/readme", wrapper.GetRepositoryReadme)

	return m
}
