// Package identityclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package identityclient

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccessSourceKind.
const (
	AccessSourceKindDirect            AccessSourceKind = "direct"
	AccessSourceKindInstallationAdmin AccessSourceKind = "installation_admin"
	AccessSourceKindInternal          AccessSourceKind = "internal"
	AccessSourceKindOwner             AccessSourceKind = "owner"
	AccessSourceKindTeam              AccessSourceKind = "team"
)

// Valid indicates whether the value is a known member of the AccessSourceKind enum.
func (e AccessSourceKind) Valid() bool {
	switch e {
	case AccessSourceKindDirect:
		return true
	case AccessSourceKindInstallationAdmin:
		return true
	case AccessSourceKindInternal:
		return true
	case AccessSourceKindOwner:
		return true
	case AccessSourceKindTeam:
		return true
	default:
		return false
	}
}

// Defines values for GrantSubjectType.
const (
	GrantSubjectTypeTeam GrantSubjectType = "team"
	GrantSubjectTypeUser GrantSubjectType = "user"
)

// Valid indicates whether the value is a known member of the GrantSubjectType enum.
func (e GrantSubjectType) Valid() bool {
	switch e {
	case GrantSubjectTypeTeam:
		return true
	case GrantSubjectTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for LookupEmailsResultUsersKind.
const (
	LookupEmailsResultUsersKindAgent LookupEmailsResultUsersKind = "agent"
	LookupEmailsResultUsersKindHuman LookupEmailsResultUsersKind = "human"
)

// Valid indicates whether the value is a known member of the LookupEmailsResultUsersKind enum.
func (e LookupEmailsResultUsersKind) Valid() bool {
	switch e {
	case LookupEmailsResultUsersKindAgent:
		return true
	case LookupEmailsResultUsersKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for LookupIdsResultUsersKind.
const (
	LookupIdsResultUsersKindAgent LookupIdsResultUsersKind = "agent"
	LookupIdsResultUsersKindHuman LookupIdsResultUsersKind = "human"
)

// Valid indicates whether the value is a known member of the LookupIdsResultUsersKind enum.
func (e LookupIdsResultUsersKind) Valid() bool {
	switch e {
	case LookupIdsResultUsersKindAgent:
		return true
	case LookupIdsResultUsersKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for OwnerType.
const (
	OwnerTypeOrganization OwnerType = "organization"
	OwnerTypeUser         OwnerType = "user"
)

// Valid indicates whether the value is a known member of the OwnerType enum.
func (e OwnerType) Valid() bool {
	switch e {
	case OwnerTypeOrganization:
		return true
	case OwnerTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for PrincipalAuthMethod.
const (
	PrincipalAuthMethodOidc     PrincipalAuthMethod = "oidc"
	PrincipalAuthMethodPassword PrincipalAuthMethod = "password"
	PrincipalAuthMethodToken    PrincipalAuthMethod = "token"
)

// Valid indicates whether the value is a known member of the PrincipalAuthMethod enum.
func (e PrincipalAuthMethod) Valid() bool {
	switch e {
	case PrincipalAuthMethodOidc:
		return true
	case PrincipalAuthMethodPassword:
		return true
	case PrincipalAuthMethodToken:
		return true
	default:
		return false
	}
}

// Defines values for PrincipalKind.
const (
	PrincipalKindAgent PrincipalKind = "agent"
	PrincipalKindHuman PrincipalKind = "human"
)

// Valid indicates whether the value is a known member of the PrincipalKind enum.
func (e PrincipalKind) Valid() bool {
	switch e {
	case PrincipalKindAgent:
		return true
	case PrincipalKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for RepoVisibility.
const (
	RepoVisibilityInternal RepoVisibility = "internal"
	RepoVisibilityPrivate  RepoVisibility = "private"
)

// Valid indicates whether the value is a known member of the RepoVisibility enum.
func (e RepoVisibility) Valid() bool {
	switch e {
	case RepoVisibilityInternal:
		return true
	case RepoVisibilityPrivate:
		return true
	default:
		return false
	}
}

// Defines values for ResolveMentionsResultTeamsMembersKind.
const (
	ResolveMentionsResultTeamsMembersKindAgent ResolveMentionsResultTeamsMembersKind = "agent"
	ResolveMentionsResultTeamsMembersKindHuman ResolveMentionsResultTeamsMembersKind = "human"
)

// Valid indicates whether the value is a known member of the ResolveMentionsResultTeamsMembersKind enum.
func (e ResolveMentionsResultTeamsMembersKind) Valid() bool {
	switch e {
	case ResolveMentionsResultTeamsMembersKindAgent:
		return true
	case ResolveMentionsResultTeamsMembersKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for ResolveMentionsResultUsersKind.
const (
	ResolveMentionsResultUsersKindAgent ResolveMentionsResultUsersKind = "agent"
	ResolveMentionsResultUsersKindHuman ResolveMentionsResultUsersKind = "human"
)

// Valid indicates whether the value is a known member of the ResolveMentionsResultUsersKind enum.
func (e ResolveMentionsResultUsersKind) Valid() bool {
	switch e {
	case ResolveMentionsResultUsersKindAgent:
		return true
	case ResolveMentionsResultUsersKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for ResourceRole.
const (
	Admin ResourceRole = "admin"
	Read  ResourceRole = "read"
	Write ResourceRole = "write"
)

// Valid indicates whether the value is a known member of the ResourceRole enum.
func (e ResourceRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for TokenScope.
const (
	AdminOrg      TokenScope = "admin:org"
	ReadOrg       TokenScope = "read:org"
	ReadResource  TokenScope = "read:resource"
	ReadUser      TokenScope = "read:user"
	WriteOrg      TokenScope = "write:org"
	WriteResource TokenScope = "write:resource"
	WriteUser     TokenScope = "write:user"
)

// Valid indicates whether the value is a known member of the TokenScope enum.
func (e TokenScope) Valid() bool {
	switch e {
	case AdminOrg:
		return true
	case ReadOrg:
		return true
	case ReadResource:
		return true
	case ReadUser:
		return true
	case WriteOrg:
		return true
	case WriteResource:
		return true
	case WriteUser:
		return true
	default:
		return false
	}
}

// Defines values for UserKind.
const (
	UserKindAgent UserKind = "agent"
	UserKindHuman UserKind = "human"
)

// Valid indicates whether the value is a known member of the UserKind enum.
func (e UserKind) Valid() bool {
	switch e {
	case UserKindAgent:
		return true
	case UserKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for VerifyCredentialInputKind.
const (
	VerifyCredentialInputKindSession VerifyCredentialInputKind = "session"
	VerifyCredentialInputKindToken   VerifyCredentialInputKind = "token"
)

// Valid indicates whether the value is a known member of the VerifyCredentialInputKind enum.
func (e VerifyCredentialInputKind) Valid() bool {
	switch e {
	case VerifyCredentialInputKindSession:
		return true
	case VerifyCredentialInputKindToken:
		return true
	default:
		return false
	}
}

// AccessSource Una fonte del ruolo su un repo. `direct`: grant all'utente; `team`: grant al team `organization`/`team` (di cui e' membro o la cui organizzazione possiede); `owner`: owner dell'organizzazione proprietaria (`organization`) o proprietario del repo personale (P1, P6), sempre `admin`; `internal`: visibilita' interna (P3), `read`; `installation_admin`: amministratore dell'installazione, `admin`.
type AccessSource struct {
	Kind AccessSourceKind `json:"kind"`

	// Organization Solo per `team` e per `owner` di un'organizzazione.
	Organization *string `json:"organization,omitempty"`

	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role ResourceRole `json:"role"`

	// Team Solo per `team`.
	Team *string `json:"team,omitempty"`
}

// AccessSourceKind defines model for AccessSource.Kind.
type AccessSourceKind string

// CheckPermissionInput defines model for CheckPermissionInput.
type CheckPermissionInput struct {
	ResourceId openapi_types.UUID `json:"resourceId"`

	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role   ResourceRole       `json:"role"`
	UserId openapi_types.UUID `json:"userId"`
}

// CheckPermissionResult defines model for CheckPermissionResult.
type CheckPermissionResult struct {
	Allowed       bool          `json:"allowed"`
	EffectiveRole *ResourceRole `json:"effectiveRole,omitempty"`
}

// Error Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Error struct {
	Error struct {
		// Code Codice stabile leggibile da macchina (es. `not_found`).
		//
		// Example: not_found
		Code string `json:"code"`

		// Details Dettagli opzionali specifici dell'errore.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Messaggio leggibile da persone, non contrattuale.
		Message string `json:"message"`
	} `json:"error"`
}

// Grant Ruolo su una risorsa generica (D15) per un utente o un team.
type Grant struct {
	CreatedAt  *time.Time          `json:"createdAt,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	ResourceId openapi_types.UUID  `json:"resourceId"`

	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role        ResourceRole       `json:"role"`
	SubjectId   openapi_types.UUID `json:"subjectId"`
	SubjectType GrantSubjectType   `json:"subjectType"`
}

// GrantSubjectType defines model for Grant.SubjectType.
type GrantSubjectType string

// GrantResourceCreatorInput defines model for GrantResourceCreatorInput.
type GrantResourceCreatorInput struct {
	UserId openapi_types.UUID `json:"userId"`
}

// LookupEmailsInput defines model for LookupEmailsInput.
type LookupEmailsInput struct {
	Emails []string `json:"emails"`
}

// LookupEmailsResult defines model for LookupEmailsResult.
type LookupEmailsResult struct {
	// Users Solo le email che corrispondono a un utente; le altre mancano.
	Users []struct {
		AvatarUrl *string                     `json:"avatarUrl"`
		Email     string                      `json:"email"`
		Id        openapi_types.UUID          `json:"id"`
		Kind      LookupEmailsResultUsersKind `json:"kind"`

		// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
		//
		//
		// Example: alice
		Username Name `json:"username"`
	} `json:"users"`
}

// LookupEmailsResultUsersKind defines model for LookupEmailsResult.Users.Kind.
type LookupEmailsResultUsersKind string

// LookupIdsInput defines model for LookupIdsInput.
type LookupIdsInput struct {
	Ids []openapi_types.UUID `json:"ids"`
}

// LookupIdsResult defines model for LookupIdsResult.
type LookupIdsResult struct {
	Users []struct {
		// Email Email dell'utente, se ne ha una (M-06/F, C5: core la usa per le notifiche email, mai per gli agenti). Assente senza email.
		Email *string                  `json:"email,omitempty"`
		Id    openapi_types.UUID       `json:"id"`
		Kind  LookupIdsResultUsersKind `json:"kind"`

		// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
		//
		//
		// Example: alice
		Username Name `json:"username"`
	} `json:"users"`
}

// LookupIdsResultUsersKind defines model for LookupIdsResult.Users.Kind.
type LookupIdsResultUsersKind string

// Name Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type Name = string

// OrgOwnersResult defines model for OrgOwnersResult.
type OrgOwnersResult struct {
	Owners []openapi_types.UUID `json:"owners"`
}

// OwnerRef defines model for OwnerRef.
type OwnerRef struct {
	Id openapi_types.UUID `json:"id"`

	// Name Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Name Name      `json:"name"`
	Type OwnerType `json:"type"`
}

// OwnerType defines model for OwnerType.
type OwnerType string

// Principal Chi ha presentato la credenziale.
type Principal struct {
	AuthMethod PrincipalAuthMethod `json:"authMethod"`

	// CredentialId Id della sessione o del token (per audit).
	CredentialId *openapi_types.UUID `json:"credentialId,omitempty"`
	ExpiresAt    *time.Time          `json:"expiresAt,omitempty"`
	IsAdmin      bool                `json:"isAdmin"`
	Kind         PrincipalKind       `json:"kind"`

	// MustChangePassword Vero per una sessione la cui password iniziale non e' ancora stata cambiata (vedi `CurrentSession.mustChangePassword`). `/internal/verify` risponde comunque `active` true: il gateway risponde 403 `password_change_required` a ogni rotta tranne `GET /auth/session`, `POST /auth/logout` e `PUT /users/{username}/password` sulla propria utenza. Assente equivale a falso.
	MustChangePassword *bool `json:"mustChangePassword,omitempty"`

	// Scopes Solo per i token; assenti per le sessioni.
	Scopes *[]TokenScope `json:"scopes,omitempty"`

	// TokenName Nome del token; presente solo con `authMethod` token.
	TokenName *string            `json:"tokenName,omitempty"`
	UserId    openapi_types.UUID `json:"userId"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// PrincipalAuthMethod defines model for Principal.AuthMethod.
type PrincipalAuthMethod string

// PrincipalKind defines model for Principal.Kind.
type PrincipalKind string

// ReadableResourcesInput defines model for ReadableResourcesInput.
type ReadableResourcesInput struct {
	UserId openapi_types.UUID `json:"userId"`
}

// ReadableResourcesResult defines model for ReadableResourcesResult.
type ReadableResourcesResult struct {
	All         bool                 `json:"all"`
	ResourceIds []openapi_types.UUID `json:"resourceIds"`
}

// RepoName Nome di un repo (R11): lettere maiuscole e minuscole, cifre, `-`, `_`, `.`; 1-100 caratteri; non inizia con `.`; non finisce con `.git` (regola applicata dal servizio, non esprimibile nel pattern). Le maiuscole sono conservate come scritte; l'unicita' per owner e il lookup non distinguono maiuscole e minuscole (`GitStack` e `gitstack` sono lo stesso repo).
//
// Example: my-app
type RepoName = string

// RepoVisibility Visibilita' (P7): `private` (solo chi ha un grant) o `internal` (tutti gli utenti dell'installazione). Nessun accesso anonimo.
type RepoVisibility string

// ResolveMentionsInput defines model for ResolveMentionsInput.
type ResolveMentionsInput struct {
	Names []string `json:"names"`
}

// ResolveMentionsResult defines model for ResolveMentionsResult.
type ResolveMentionsResult struct {
	Teams []struct {
		Members []struct {
			Id   openapi_types.UUID                    `json:"id"`
			Kind ResolveMentionsResultTeamsMembersKind `json:"kind"`

			// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
			//
			//
			// Example: alice
			Username Name `json:"username"`
		} `json:"members"`

		// Name Il nome `org/team` cosi' come e' stato chiesto.
		Name string `json:"name"`
	} `json:"teams"`
	Users []struct {
		Id   openapi_types.UUID             `json:"id"`
		Kind ResolveMentionsResultUsersKind `json:"kind"`

		// Name Il nome cosi' come e' stato chiesto.
		Name string `json:"name"`

		// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
		//
		//
		// Example: alice
		Username Name `json:"username"`
	} `json:"users"`
}

// ResolveMentionsResultTeamsMembersKind defines model for ResolveMentionsResult.Teams.Members.Kind.
type ResolveMentionsResultTeamsMembersKind string

// ResolveMentionsResultUsersKind defines model for ResolveMentionsResult.Users.Kind.
type ResolveMentionsResultUsersKind string

// ResourceAttributesInput defines model for ResourceAttributesInput.
type ResourceAttributesInput struct {
	OwnerId   openapi_types.UUID `json:"ownerId"`
	OwnerType OwnerType          `json:"ownerType"`

	// Visibility Visibilita' (P7): `private` (solo chi ha un grant) o `internal` (tutti gli utenti dell'installazione). Nessun accesso anonimo.
	Visibility RepoVisibility `json:"visibility"`
}

// ResourceRole Ruolo su una risorsa, in ordine crescente di potere.
type ResourceRole string

// SshKey defines model for SshKey.
type SshKey struct {
	CreatedAt   time.Time           `json:"createdAt"`
	Fingerprint string              `json:"fingerprint"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KeyType Example: ssh-ed25519
	KeyType    string     `json:"keyType"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	Title      string     `json:"title"`
}

// SshKeyLookup defines model for SshKeyLookup.
type SshKeyLookup struct {
	Key SshKey `json:"key"`

	// User Profilo utente. `email`, `isAdmin`, `isActive`, `createdAt` sono presenti solo per l'utente stesso e per gli amministratori.
	User User `json:"user"`
}

// TokenScope Catalogo degli scope dei token personali (unico, condiviso da tutti i servizi). Le sessioni web non hanno scope: valgono i permessi dell'utente. `write:*` include `read:*` dello stesso ambito; `admin:org` include `write:org`.
type TokenScope string

// User Profilo utente. `email`, `isAdmin`, `isActive`, `createdAt` sono presenti solo per l'utente stesso e per gli amministratori.
type User struct {
	AvatarUrl   *string              `json:"avatarUrl,omitempty"`
	Bio         *string              `json:"bio,omitempty"`
	CreatedAt   *time.Time           `json:"createdAt,omitempty"`
	DisplayName string               `json:"displayName"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Id          *openapi_types.UUID  `json:"id,omitempty"`
	IsActive    *bool                `json:"isActive,omitempty"`
	IsAdmin     *bool                `json:"isAdmin,omitempty"`
	Kind        UserKind             `json:"kind"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// UserKind defines model for User.Kind.
type UserKind string

// UserAccessSources defines model for UserAccessSources.
type UserAccessSources struct {
	Admin bool                    `json:"admin"`
	Items []UserAccessSourcesItem `json:"items"`
}

// UserAccessSourcesItem defines model for UserAccessSourcesItem.
type UserAccessSourcesItem struct {
	ResourceId openapi_types.UUID `json:"resourceId"`

	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role    ResourceRole   `json:"role"`
	Sources []AccessSource `json:"sources"`
}

// VerifyCredentialInput defines model for VerifyCredentialInput.
type VerifyCredentialInput struct {
	// Credential Valore grezzo della credenziale (cookie `gst_session` o token `gst_...`).
	Credential *string `json:"credential,omitempty"`

	// Kind Facoltativo, evita l'ambiguita' se il gateway la conosce.
	Kind *VerifyCredentialInputKind `json:"kind,omitempty"`
}

// VerifyCredentialInputKind Facoltativo, evita l'ambiguita' se il gateway la conosce.
type VerifyCredentialInputKind string

// VerifyCredentialResult defines model for VerifyCredentialResult.
type VerifyCredentialResult struct {
	Active bool `json:"active"`

	// CacheTtlSeconds Per quanto tempo il gateway puo' tenere in cache l'esito.
	CacheTtlSeconds *int `json:"cacheTtlSeconds,omitempty"`

	// Principal Chi ha presentato la credenziale.
	Principal *Principal `json:"principal,omitempty"`
}

// CommitShaParam defines model for CommitShaParam.
type CommitShaParam = string

// GitRepoIdParam defines model for GitRepoIdParam.
type GitRepoIdParam = openapi_types.UUID

// GrantIdParam defines model for GrantIdParam.
type GrantIdParam = openapi_types.UUID

// IssueAttachmentIdParam defines model for IssueAttachmentIdParam.
type IssueAttachmentIdParam = openapi_types.UUID

// IssueCommentIdParam defines model for IssueCommentIdParam.
type IssueCommentIdParam = openapi_types.UUID

// IssueNumberParam defines model for IssueNumberParam.
type IssueNumberParam = int64

// LabelNameParam defines model for LabelNameParam.
type LabelNameParam = string

// MilestoneNumberParam defines model for MilestoneNumberParam.
type MilestoneNumberParam = int64

// MirrorIdParam defines model for MirrorIdParam.
type MirrorIdParam = openapi_types.UUID

// NotificationIdParam defines model for NotificationIdParam.
type NotificationIdParam = openapi_types.UUID

// OidcProviderParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OidcProviderParam = Name

// OrgParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OrgParam = Name

// RefAndPathParam defines model for RefAndPathParam.
type RefAndPathParam = string

// RepoNameParam Nome di un repo (R11): lettere maiuscole e minuscole, cifre, `-`, `_`, `.`; 1-100 caratteri; non inizia con `.`; non finisce con `.git` (regola applicata dal servizio, non esprimibile nel pattern). Le maiuscole sono conservate come scritte; l'unicita' per owner e il lookup non distinguono maiuscole e minuscole (`GitStack` e `gitstack` sono lo stesso repo).
//
// Example: my-app
type RepoNameParam = RepoName

// RepoOwnerParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type RepoOwnerParam = Name

// ResourceIdParam defines model for ResourceIdParam.
type ResourceIdParam = openapi_types.UUID

// SshKeyIdParam defines model for SshKeyIdParam.
type SshKeyIdParam = openapi_types.UUID

// TeamParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type TeamParam = Name

// TokenIdParam defines model for TokenIdParam.
type TokenIdParam = openapi_types.UUID

// UsernameParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type UsernameParam = Name

// WebhookDeliveryIdParam defines model for WebhookDeliveryIdParam.
type WebhookDeliveryIdParam = openapi_types.UUID

// WebhookIdParam defines model for WebhookIdParam.
type WebhookIdParam = openapi_types.UUID

// BadRequest Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type BadRequest = Error

// Conflict Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Conflict = Error

// NotFound Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type NotFound = Error

// Unauthorized Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Unauthorized = Error

// UnexpectedError Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type UnexpectedError = Error

// ResolveMentionsJSONRequestBody defines body for ResolveMentions for application/json ContentType.
type ResolveMentionsJSONRequestBody = ResolveMentionsInput

// CheckPermissionJSONRequestBody defines body for CheckPermission for application/json ContentType.
type CheckPermissionJSONRequestBody = CheckPermissionInput

// ListReadableResourcesJSONRequestBody defines body for ListReadableResources for application/json ContentType.
type ListReadableResourcesJSONRequestBody = ReadableResourcesInput

// GetUserAccessSourcesJSONRequestBody defines body for GetUserAccessSources for application/json ContentType.
type GetUserAccessSourcesJSONRequestBody = ReadableResourcesInput

// SetResourceAttributesJSONRequestBody defines body for SetResourceAttributes for application/json ContentType.
type SetResourceAttributesJSONRequestBody = ResourceAttributesInput

// GrantResourceCreatorJSONRequestBody defines body for GrantResourceCreator for application/json ContentType.
type GrantResourceCreatorJSONRequestBody = GrantResourceCreatorInput

// LookupUsersByEmailJSONRequestBody defines body for LookupUsersByEmail for application/json ContentType.
type LookupUsersByEmailJSONRequestBody = LookupEmailsInput

// LookupUsersByIdsJSONRequestBody defines body for LookupUsersByIds for application/json ContentType.
type LookupUsersByIdsJSONRequestBody = LookupIdsInput

// VerifyCredentialJSONRequestBody defines body for VerifyCredential for application/json ContentType.
type VerifyCredentialJSONRequestBody = VerifyCredentialInput
