// Package identityclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package identityclient

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GrantSubjectType.
const (
	GrantSubjectTypeTeam GrantSubjectType = "team"
	GrantSubjectTypeUser GrantSubjectType = "user"
)

// Valid indicates whether the value is a known member of the GrantSubjectType enum.
func (e GrantSubjectType) Valid() bool {
	switch e {
	case GrantSubjectTypeTeam:
		return true
	case GrantSubjectTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for PrincipalAuthMethod.
const (
	PrincipalAuthMethodOidc     PrincipalAuthMethod = "oidc"
	PrincipalAuthMethodPassword PrincipalAuthMethod = "password"
	PrincipalAuthMethodToken    PrincipalAuthMethod = "token"
)

// Valid indicates whether the value is a known member of the PrincipalAuthMethod enum.
func (e PrincipalAuthMethod) Valid() bool {
	switch e {
	case PrincipalAuthMethodOidc:
		return true
	case PrincipalAuthMethodPassword:
		return true
	case PrincipalAuthMethodToken:
		return true
	default:
		return false
	}
}

// Defines values for PrincipalKind.
const (
	PrincipalKindAgent PrincipalKind = "agent"
	PrincipalKindHuman PrincipalKind = "human"
)

// Valid indicates whether the value is a known member of the PrincipalKind enum.
func (e PrincipalKind) Valid() bool {
	switch e {
	case PrincipalKindAgent:
		return true
	case PrincipalKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for ResourceRole.
const (
	Admin ResourceRole = "admin"
	Read  ResourceRole = "read"
	Write ResourceRole = "write"
)

// Valid indicates whether the value is a known member of the ResourceRole enum.
func (e ResourceRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for TokenScope.
const (
	AdminOrg      TokenScope = "admin:org"
	ReadOrg       TokenScope = "read:org"
	ReadResource  TokenScope = "read:resource"
	ReadUser      TokenScope = "read:user"
	WriteOrg      TokenScope = "write:org"
	WriteResource TokenScope = "write:resource"
	WriteUser     TokenScope = "write:user"
)

// Valid indicates whether the value is a known member of the TokenScope enum.
func (e TokenScope) Valid() bool {
	switch e {
	case AdminOrg:
		return true
	case ReadOrg:
		return true
	case ReadResource:
		return true
	case ReadUser:
		return true
	case WriteOrg:
		return true
	case WriteResource:
		return true
	case WriteUser:
		return true
	default:
		return false
	}
}

// Defines values for UserKind.
const (
	UserKindAgent UserKind = "agent"
	UserKindHuman UserKind = "human"
)

// Valid indicates whether the value is a known member of the UserKind enum.
func (e UserKind) Valid() bool {
	switch e {
	case UserKindAgent:
		return true
	case UserKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for VerifyCredentialInputKind.
const (
	VerifyCredentialInputKindSession VerifyCredentialInputKind = "session"
	VerifyCredentialInputKindToken   VerifyCredentialInputKind = "token"
)

// Valid indicates whether the value is a known member of the VerifyCredentialInputKind enum.
func (e VerifyCredentialInputKind) Valid() bool {
	switch e {
	case VerifyCredentialInputKindSession:
		return true
	case VerifyCredentialInputKindToken:
		return true
	default:
		return false
	}
}

// CheckPermissionInput defines model for CheckPermissionInput.
type CheckPermissionInput struct {
	ResourceId openapi_types.UUID `json:"resourceId"`

	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role   ResourceRole       `json:"role"`
	UserId openapi_types.UUID `json:"userId"`
}

// CheckPermissionResult defines model for CheckPermissionResult.
type CheckPermissionResult struct {
	Allowed       bool          `json:"allowed"`
	EffectiveRole *ResourceRole `json:"effectiveRole,omitempty"`
}

// Error Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Error struct {
	Error struct {
		// Code Codice stabile leggibile da macchina (es. `not_found`).
		//
		// Example: not_found
		Code string `json:"code"`

		// Details Dettagli opzionali specifici dell'errore.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Messaggio leggibile da persone, non contrattuale.
		Message string `json:"message"`
	} `json:"error"`
}

// Grant Ruolo su una risorsa generica (D15) per un utente o un team.
type Grant struct {
	CreatedAt  *time.Time          `json:"createdAt,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	ResourceId openapi_types.UUID  `json:"resourceId"`

	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role        ResourceRole       `json:"role"`
	SubjectId   openapi_types.UUID `json:"subjectId"`
	SubjectType GrantSubjectType   `json:"subjectType"`
}

// GrantSubjectType defines model for Grant.SubjectType.
type GrantSubjectType string

// GrantResourceCreatorInput defines model for GrantResourceCreatorInput.
type GrantResourceCreatorInput struct {
	UserId openapi_types.UUID `json:"userId"`
}

// Name Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type Name = string

// Principal Chi ha presentato la credenziale.
type Principal struct {
	AuthMethod PrincipalAuthMethod `json:"authMethod"`

	// CredentialId Id della sessione o del token (per audit).
	CredentialId *openapi_types.UUID `json:"credentialId,omitempty"`
	ExpiresAt    *time.Time          `json:"expiresAt,omitempty"`
	IsAdmin      bool                `json:"isAdmin"`
	Kind         PrincipalKind       `json:"kind"`

	// MustChangePassword Vero per una sessione la cui password iniziale non e' ancora stata cambiata (vedi `CurrentSession.mustChangePassword`). `/internal/verify` risponde comunque `active` true: il gateway risponde 403 `password_change_required` a ogni rotta tranne `GET /auth/session`, `POST /auth/logout` e `PUT /users/{username}/password` sulla propria utenza. Assente equivale a falso.
	MustChangePassword *bool `json:"mustChangePassword,omitempty"`

	// Scopes Solo per i token; assenti per le sessioni.
	Scopes *[]TokenScope      `json:"scopes,omitempty"`
	UserId openapi_types.UUID `json:"userId"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// PrincipalAuthMethod defines model for Principal.AuthMethod.
type PrincipalAuthMethod string

// PrincipalKind defines model for Principal.Kind.
type PrincipalKind string

// ResourceRole Ruolo su una risorsa, in ordine crescente di potere.
type ResourceRole string

// SshKey defines model for SshKey.
type SshKey struct {
	CreatedAt   time.Time           `json:"createdAt"`
	Fingerprint string              `json:"fingerprint"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KeyType Example: ssh-ed25519
	KeyType    string     `json:"keyType"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	Title      string     `json:"title"`
}

// SshKeyLookup defines model for SshKeyLookup.
type SshKeyLookup struct {
	Key SshKey `json:"key"`

	// User Profilo utente. `email`, `isAdmin`, `isActive`, `createdAt` sono presenti solo per l'utente stesso e per gli amministratori.
	User User `json:"user"`
}

// TokenScope Catalogo degli scope dei token personali (unico, condiviso da tutti i servizi). Le sessioni web non hanno scope: valgono i permessi dell'utente. `write:*` include `read:*` dello stesso ambito; `admin:org` include `write:org`.
type TokenScope string

// User Profilo utente. `email`, `isAdmin`, `isActive`, `createdAt` sono presenti solo per l'utente stesso e per gli amministratori.
type User struct {
	AvatarUrl   *string              `json:"avatarUrl,omitempty"`
	Bio         *string              `json:"bio,omitempty"`
	CreatedAt   *time.Time           `json:"createdAt,omitempty"`
	DisplayName string               `json:"displayName"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Id          *openapi_types.UUID  `json:"id,omitempty"`
	IsActive    *bool                `json:"isActive,omitempty"`
	IsAdmin     *bool                `json:"isAdmin,omitempty"`
	Kind        UserKind             `json:"kind"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// UserKind defines model for User.Kind.
type UserKind string

// VerifyCredentialInput defines model for VerifyCredentialInput.
type VerifyCredentialInput struct {
	// Credential Valore grezzo della credenziale (cookie `gst_session` o token `gst_...`).
	Credential *string `json:"credential,omitempty"`

	// Kind Facoltativo, evita l'ambiguita' se il gateway la conosce.
	Kind *VerifyCredentialInputKind `json:"kind,omitempty"`
}

// VerifyCredentialInputKind Facoltativo, evita l'ambiguita' se il gateway la conosce.
type VerifyCredentialInputKind string

// VerifyCredentialResult defines model for VerifyCredentialResult.
type VerifyCredentialResult struct {
	Active bool `json:"active"`

	// CacheTtlSeconds Per quanto tempo il gateway puo' tenere in cache l'esito.
	CacheTtlSeconds *int `json:"cacheTtlSeconds,omitempty"`

	// Principal Chi ha presentato la credenziale.
	Principal *Principal `json:"principal,omitempty"`
}

// GrantIdParam defines model for GrantIdParam.
type GrantIdParam = openapi_types.UUID

// OidcProviderParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OidcProviderParam = Name

// OrgParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OrgParam = Name

// ResourceIdParam defines model for ResourceIdParam.
type ResourceIdParam = openapi_types.UUID

// SshKeyIdParam defines model for SshKeyIdParam.
type SshKeyIdParam = openapi_types.UUID

// TeamParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type TeamParam = Name

// TokenIdParam defines model for TokenIdParam.
type TokenIdParam = openapi_types.UUID

// UsernameParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type UsernameParam = Name

// BadRequest Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type BadRequest = Error

// NotFound Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type NotFound = Error

// Unauthorized Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Unauthorized = Error

// UnexpectedError Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type UnexpectedError = Error

// CheckPermissionJSONRequestBody defines body for CheckPermission for application/json ContentType.
type CheckPermissionJSONRequestBody = CheckPermissionInput

// GrantResourceCreatorJSONRequestBody defines body for GrantResourceCreator for application/json ContentType.
type GrantResourceCreatorJSONRequestBody = GrantResourceCreatorInput

// VerifyCredentialJSONRequestBody defines body for VerifyCredential for application/json ContentType.
type VerifyCredentialJSONRequestBody = VerifyCredentialInput
