// Package gitstack provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package gitstack

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// CreateResourceInput defines model for CreateResourceInput.
type CreateResourceInput struct {
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	Name       string                  `json:"name"`

	// Type Example: repo
	Type string `json:"type"`
}

// Error Formato unico degli errori per tutta l'API pubblica.
type Error struct {
	Error struct {
		// Code Codice stabile leggibile da macchina (es. `not_found`).
		//
		// Example: not_found
		Code string `json:"code"`

		// Details Dettagli opzionali specifici dell'errore.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Messaggio leggibile da persone, non contrattuale.
		Message string `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Versione del contratto API in esecuzione (`info.version`).
	Version string `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Resource Risorsa generica (D15): oggi usata dalla prova end-to-end, in futuro anche per repository, applicazioni e database, senza cambiare forma.
type Resource struct {
	// Attributes Attributi specifici del tipo di risorsa, a forma libera.
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	CreatedAt  *time.Time              `json:"createdAt,omitempty"`
	Id         *openapi_types.UUID     `json:"id,omitempty"`
	Name       string                  `json:"name"`

	// Type Tipo di risorsa, aperto: non un enum fisso (D15).
	//
	// Example: repo
	Type      string     `json:"type"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ResourceList defines model for ResourceList.
type ResourceList struct {
	Items   []Resource `json:"items"`
	Page    int        `json:"page"`
	PerPage int        `json:"perPage"`
	Total   int        `json:"total"`
}

// UpdateResourceInput defines model for UpdateResourceInput.
type UpdateResourceInput struct {
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	Name       *string                 `json:"name,omitempty"`
}

// PageParam defines model for PageParam.
type PageParam = int

// PerPageParam defines model for PerPageParam.
type PerPageParam = int

// ResourceIdParam defines model for ResourceIdParam.
type ResourceIdParam = openapi_types.UUID

// ResourceTypeFilter defines model for ResourceTypeFilter.
type ResourceTypeFilter = string

// BadRequest Formato unico degli errori per tutta l'API pubblica.
type BadRequest = Error

// Conflict Formato unico degli errori per tutta l'API pubblica.
type Conflict = Error

// NotFound Formato unico degli errori per tutta l'API pubblica.
type NotFound = Error

// Unauthorized Formato unico degli errori per tutta l'API pubblica.
type Unauthorized = Error

// UnexpectedError Formato unico degli errori per tutta l'API pubblica.
type UnexpectedError = Error

// ListResourcesParams defines parameters for ListResources.
type ListResourcesParams struct {
	// Type Filtra per tipo di risorsa (es. `repo`).
	Type    *ResourceTypeFilter `form:"type,omitempty" json:"type,omitempty"`
	Page    *PageParam          `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageParam       `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// CreateResourceJSONRequestBody defines body for CreateResource for application/json ContentType.
type CreateResourceJSONRequestBody = CreateResourceInput

// UpdateResourceJSONRequestBody defines body for UpdateResource for application/json ContentType.
type UpdateResourceJSONRequestBody = UpdateResourceInput

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetHealth Stato del servizio
	//
	// Controllo di salute, senza autenticazione: usato da orchestratore (k3s) e dai probe di deploy.
	//
	// Corresponds with GET /health (the `GetHealth` operationId).
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListResources Elenca le risorse
	//
	// Elenco paginato delle risorse, con filtro opzionale per tipo (es. `repo`). Il tipo non è vincolato a un insieme fisso: nuove milestone aggiungono nuovi tipi senza cambiare l'endpoint (D15).
	//
	// Corresponds with GET /resources (the `ListResources` operationId).
	ListResources(ctx context.Context, params *ListResourcesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateResourceWithBody Crea una risorsa
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /resources (the `CreateResource` operationId).
	CreateResourceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateResource Crea una risorsa
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /resources (the `CreateResource` operationId).
	CreateResource(ctx context.Context, body CreateResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteResource Elimina una risorsa
	//
	// Corresponds with DELETE /resources/{resourceId} (the `DeleteResource` operationId).
	DeleteResource(ctx context.Context, resourceId ResourceIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetResource Legge una risorsa
	//
	// Corresponds with GET /resources/{resourceId} (the `GetResource` operationId).
	GetResource(ctx context.Context, resourceId ResourceIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateResourceWithBody Aggiorna una risorsa
	//
	// Aggiornamento parziale: solo i campi presenti nel corpo cambiano.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /resources/{resourceId} (the `UpdateResource` operationId).
	UpdateResourceWithBody(ctx context.Context, resourceId ResourceIdParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateResource Aggiorna una risorsa
	//
	// Aggiornamento parziale: solo i campi presenti nel corpo cambiano.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PATCH /resources/{resourceId} (the `UpdateResource` operationId).
	UpdateResource(ctx context.Context, resourceId ResourceIdParam, body UpdateResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetHealth Stato del servizio
//
// Controllo di salute, senza autenticazione: usato da orchestratore (k3s) e dai probe di deploy.
//
// Corresponds with GET /health (the `GetHealth` operationId).
func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListResources Elenca le risorse
//
// Elenco paginato delle risorse, con filtro opzionale per tipo (es. `repo`). Il tipo non è vincolato a un insieme fisso: nuove milestone aggiungono nuovi tipi senza cambiare l'endpoint (D15).
//
// Corresponds with GET /resources (the `ListResources` operationId).
func (c *Client) ListResources(ctx context.Context, params *ListResourcesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListResourcesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateResourceWithBody Crea una risorsa
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /resources (the `CreateResource` operationId).
func (c *Client) CreateResourceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateResourceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateResource Crea una risorsa
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /resources (the `CreateResource` operationId).
func (c *Client) CreateResource(ctx context.Context, body CreateResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateResourceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteResource Elimina una risorsa
//
// Corresponds with DELETE /resources/{resourceId} (the `DeleteResource` operationId).
func (c *Client) DeleteResource(ctx context.Context, resourceId ResourceIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteResourceRequest(c.Server, resourceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetResource Legge una risorsa
//
// Corresponds with GET /resources/{resourceId} (the `GetResource` operationId).
func (c *Client) GetResource(ctx context.Context, resourceId ResourceIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetResourceRequest(c.Server, resourceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateResourceWithBody Aggiorna una risorsa
//
// Aggiornamento parziale: solo i campi presenti nel corpo cambiano.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /resources/{resourceId} (the `UpdateResource` operationId).
func (c *Client) UpdateResourceWithBody(ctx context.Context, resourceId ResourceIdParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateResourceRequestWithBody(c.Server, resourceId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateResource Aggiorna una risorsa
//
// Aggiornamento parziale: solo i campi presenti nel corpo cambiano.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PATCH /resources/{resourceId} (the `UpdateResource` operationId).
func (c *Client) UpdateResource(ctx context.Context, resourceId ResourceIdParam, body UpdateResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateResourceRequest(c.Server, resourceId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest constructs an http.Request for the GetHealth method
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListResourcesRequest constructs an http.Request for the ListResources method
func NewListResourcesRequest(server string, params *ListResourcesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/resources")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "perPage", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateResourceRequest calls the generic CreateResource builder with application/json body
func NewCreateResourceRequest(server string, body CreateResourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateResourceRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateResourceRequestWithBody constructs an http.Request for the CreateResource method, with any body, and a specified content type
func NewCreateResourceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/resources")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteResourceRequest constructs an http.Request for the DeleteResource method
func NewDeleteResourceRequest(server string, resourceId ResourceIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "resourceId", resourceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/resources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetResourceRequest constructs an http.Request for the GetResource method
func NewGetResourceRequest(server string, resourceId ResourceIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "resourceId", resourceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/resources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateResourceRequest calls the generic UpdateResource builder with application/json body
func NewUpdateResourceRequest(server string, resourceId ResourceIdParam, body UpdateResourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateResourceRequestWithBody(server, resourceId, "application/json", bodyReader)
}

// NewUpdateResourceRequestWithBody constructs an http.Request for the UpdateResource method, with any body, and a specified content type
func NewUpdateResourceRequestWithBody(server string, resourceId ResourceIdParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "resourceId", resourceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/resources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetHealthWithResponse Stato del servizio
	//
	// Controllo di salute, senza autenticazione: usato da orchestratore (k3s) e dai probe di deploy.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /health (the `GetHealth` operationId).
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ListResourcesWithResponse Elenca le risorse
	//
	// Elenco paginato delle risorse, con filtro opzionale per tipo (es. `repo`). Il tipo non è vincolato a un insieme fisso: nuove milestone aggiungono nuovi tipi senza cambiare l'endpoint (D15).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /resources (the `ListResources` operationId).
	ListResourcesWithResponse(ctx context.Context, params *ListResourcesParams, reqEditors ...RequestEditorFn) (*ListResourcesResponse, error)

	// CreateResourceWithBodyWithResponse Crea una risorsa
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /resources (the `CreateResource` operationId).
	CreateResourceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateResourceResponse, error)

	// CreateResourceWithResponse Crea una risorsa
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /resources (the `CreateResource` operationId).
	CreateResourceWithResponse(ctx context.Context, body CreateResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateResourceResponse, error)

	// DeleteResourceWithResponse Elimina una risorsa
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /resources/{resourceId} (the `DeleteResource` operationId).
	DeleteResourceWithResponse(ctx context.Context, resourceId ResourceIdParam, reqEditors ...RequestEditorFn) (*DeleteResourceResponse, error)

	// GetResourceWithResponse Legge una risorsa
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /resources/{resourceId} (the `GetResource` operationId).
	GetResourceWithResponse(ctx context.Context, resourceId ResourceIdParam, reqEditors ...RequestEditorFn) (*GetResourceResponse, error)

	// UpdateResourceWithBodyWithResponse Aggiorna una risorsa
	//
	// Aggiornamento parziale: solo i campi presenti nel corpo cambiano.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /resources/{resourceId} (the `UpdateResource` operationId).
	UpdateResourceWithBodyWithResponse(ctx context.Context, resourceId ResourceIdParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateResourceResponse, error)

	// UpdateResourceWithResponse Aggiorna una risorsa
	//
	// Aggiornamento parziale: solo i campi presenti nel corpo cambiano.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /resources/{resourceId} (the `UpdateResource` operationId).
	UpdateResourceWithResponse(ctx context.Context, resourceId ResourceIdParam, body UpdateResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateResourceResponse, error)
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetHealthResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListResourcesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ResourceList
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *UnexpectedError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListResourcesResponse) GetJSON200() *ResourceList {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ListResourcesResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListResourcesResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ListResourcesResponse) GetJSONDefault() *UnexpectedError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ListResourcesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListResourcesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListResourcesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListResourcesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateResourceResponse201Headers the declared response headers of an HTTP 201 response for CreateResource
type CreateResourceResponse201Headers struct {
	Location *string
}

type CreateResourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Resource
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *UnexpectedError
	// Headers201 the parsed response headers for an HTTP 201 response
	Headers201 *CreateResourceResponse201Headers
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateResourceResponse) GetJSON201() *Resource {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateResourceResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreateResourceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateResourceResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r CreateResourceResponse) GetJSONDefault() *UnexpectedError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r CreateResourceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateResourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateResourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateResourceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteResourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *UnexpectedError
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeleteResourceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteResourceResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DeleteResourceResponse) GetJSONDefault() *UnexpectedError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DeleteResourceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteResourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteResourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteResourceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetResourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Resource
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *UnexpectedError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetResourceResponse) GetJSON200() *Resource {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetResourceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetResourceResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetResourceResponse) GetJSONDefault() *UnexpectedError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetResourceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetResourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetResourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetResourceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateResourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Resource
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *UnexpectedError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdateResourceResponse) GetJSON200() *Resource {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpdateResourceResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UpdateResourceResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpdateResourceResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r UpdateResourceResponse) GetJSONDefault() *UnexpectedError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r UpdateResourceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateResourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateResourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateResourceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetHealthWithResponse Stato del servizio
//
// Controllo di salute, senza autenticazione: usato da orchestratore (k3s) e dai probe di deploy.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /health (the `GetHealth` operationId).
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ListResourcesWithResponse Elenca le risorse
//
// Elenco paginato delle risorse, con filtro opzionale per tipo (es. `repo`). Il tipo non è vincolato a un insieme fisso: nuove milestone aggiungono nuovi tipi senza cambiare l'endpoint (D15).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /resources (the `ListResources` operationId).
func (c *ClientWithResponses) ListResourcesWithResponse(ctx context.Context, params *ListResourcesParams, reqEditors ...RequestEditorFn) (*ListResourcesResponse, error) {
	rsp, err := c.ListResources(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListResourcesResponse(rsp)
}

// CreateResourceWithBodyWithResponse Crea una risorsa
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /resources (the `CreateResource` operationId).
func (c *ClientWithResponses) CreateResourceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateResourceResponse, error) {
	rsp, err := c.CreateResourceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateResourceResponse(rsp)
}

// CreateResourceWithResponse Crea una risorsa
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /resources (the `CreateResource` operationId).
func (c *ClientWithResponses) CreateResourceWithResponse(ctx context.Context, body CreateResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateResourceResponse, error) {
	rsp, err := c.CreateResource(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateResourceResponse(rsp)
}

// DeleteResourceWithResponse Elimina una risorsa
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /resources/{resourceId} (the `DeleteResource` operationId).
func (c *ClientWithResponses) DeleteResourceWithResponse(ctx context.Context, resourceId ResourceIdParam, reqEditors ...RequestEditorFn) (*DeleteResourceResponse, error) {
	rsp, err := c.DeleteResource(ctx, resourceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteResourceResponse(rsp)
}

// GetResourceWithResponse Legge una risorsa
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /resources/{resourceId} (the `GetResource` operationId).
func (c *ClientWithResponses) GetResourceWithResponse(ctx context.Context, resourceId ResourceIdParam, reqEditors ...RequestEditorFn) (*GetResourceResponse, error) {
	rsp, err := c.GetResource(ctx, resourceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetResourceResponse(rsp)
}

// UpdateResourceWithBodyWithResponse Aggiorna una risorsa
//
// Aggiornamento parziale: solo i campi presenti nel corpo cambiano.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /resources/{resourceId} (the `UpdateResource` operationId).
func (c *ClientWithResponses) UpdateResourceWithBodyWithResponse(ctx context.Context, resourceId ResourceIdParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateResourceResponse, error) {
	rsp, err := c.UpdateResourceWithBody(ctx, resourceId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateResourceResponse(rsp)
}

// UpdateResourceWithResponse Aggiorna una risorsa
//
// Aggiornamento parziale: solo i campi presenti nel corpo cambiano.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /resources/{resourceId} (the `UpdateResource` operationId).
func (c *ClientWithResponses) UpdateResourceWithResponse(ctx context.Context, resourceId ResourceIdParam, body UpdateResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateResourceResponse, error) {
	rsp, err := c.UpdateResource(ctx, resourceId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateResourceResponse(rsp)
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListResourcesResponse parses an HTTP response from a ListResourcesWithResponse call
func ParseListResourcesResponse(rsp *http.Response) (*ListResourcesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListResourcesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ResourceList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest UnexpectedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateResourceResponse parses an HTTP response from a CreateResourceWithResponse call
func ParseCreateResourceResponse(rsp *http.Response) (*CreateResourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateResourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Resource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest UnexpectedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case rsp.StatusCode == 201:
		var headers CreateResourceResponse201Headers
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		response.Headers201 = &headers
	}

	return response, nil
}

// ParseDeleteResourceResponse parses an HTTP response from a DeleteResourceWithResponse call
func ParseDeleteResourceResponse(rsp *http.Response) (*DeleteResourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteResourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest UnexpectedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetResourceResponse parses an HTTP response from a GetResourceWithResponse call
func ParseGetResourceResponse(rsp *http.Response) (*GetResourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetResourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Resource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest UnexpectedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateResourceResponse parses an HTTP response from a UpdateResourceWithResponse call
func ParseUpdateResourceResponse(rsp *http.Response) (*UpdateResourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateResourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Resource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest UnexpectedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
