//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateGrantInputSubjectType.
const (
	CreateGrantInputSubjectTypeTeam CreateGrantInputSubjectType = "team"
	CreateGrantInputSubjectTypeUser CreateGrantInputSubjectType = "user"
)

// Valid indicates whether the value is a known member of the CreateGrantInputSubjectType enum.
func (e CreateGrantInputSubjectType) Valid() bool {
	switch e {
	case CreateGrantInputSubjectTypeTeam:
		return true
	case CreateGrantInputSubjectTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for CreateUserInputKind.
const (
	CreateUserInputKindAgent CreateUserInputKind = "agent"
	CreateUserInputKindHuman CreateUserInputKind = "human"
)

// Valid indicates whether the value is a known member of the CreateUserInputKind enum.
func (e CreateUserInputKind) Valid() bool {
	switch e {
	case CreateUserInputKindAgent:
		return true
	case CreateUserInputKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for CurrentSessionAuthMethod.
const (
	CurrentSessionAuthMethodOidc     CurrentSessionAuthMethod = "oidc"
	CurrentSessionAuthMethodPassword CurrentSessionAuthMethod = "password"
	CurrentSessionAuthMethodToken    CurrentSessionAuthMethod = "token"
)

// Valid indicates whether the value is a known member of the CurrentSessionAuthMethod enum.
func (e CurrentSessionAuthMethod) Valid() bool {
	switch e {
	case CurrentSessionAuthMethodOidc:
		return true
	case CurrentSessionAuthMethodPassword:
		return true
	case CurrentSessionAuthMethodToken:
		return true
	default:
		return false
	}
}

// Defines values for GrantSubjectType.
const (
	GrantSubjectTypeTeam GrantSubjectType = "team"
	GrantSubjectTypeUser GrantSubjectType = "user"
)

// Valid indicates whether the value is a known member of the GrantSubjectType enum.
func (e GrantSubjectType) Valid() bool {
	switch e {
	case GrantSubjectTypeTeam:
		return true
	case GrantSubjectTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for PrincipalAuthMethod.
const (
	PrincipalAuthMethodOidc     PrincipalAuthMethod = "oidc"
	PrincipalAuthMethodPassword PrincipalAuthMethod = "password"
	PrincipalAuthMethodToken    PrincipalAuthMethod = "token"
)

// Valid indicates whether the value is a known member of the PrincipalAuthMethod enum.
func (e PrincipalAuthMethod) Valid() bool {
	switch e {
	case PrincipalAuthMethodOidc:
		return true
	case PrincipalAuthMethodPassword:
		return true
	case PrincipalAuthMethodToken:
		return true
	default:
		return false
	}
}

// Defines values for PrincipalKind.
const (
	PrincipalKindAgent PrincipalKind = "agent"
	PrincipalKindHuman PrincipalKind = "human"
)

// Valid indicates whether the value is a known member of the PrincipalKind enum.
func (e PrincipalKind) Valid() bool {
	switch e {
	case PrincipalKindAgent:
		return true
	case PrincipalKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for ResourceRole.
const (
	Admin ResourceRole = "admin"
	Read  ResourceRole = "read"
	Write ResourceRole = "write"
)

// Valid indicates whether the value is a known member of the ResourceRole enum.
func (e ResourceRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for TokenScope.
const (
	AdminOrg      TokenScope = "admin:org"
	ReadOrg       TokenScope = "read:org"
	ReadResource  TokenScope = "read:resource"
	ReadUser      TokenScope = "read:user"
	WriteOrg      TokenScope = "write:org"
	WriteResource TokenScope = "write:resource"
	WriteUser     TokenScope = "write:user"
)

// Valid indicates whether the value is a known member of the TokenScope enum.
func (e TokenScope) Valid() bool {
	switch e {
	case AdminOrg:
		return true
	case ReadOrg:
		return true
	case ReadResource:
		return true
	case ReadUser:
		return true
	case WriteOrg:
		return true
	case WriteResource:
		return true
	case WriteUser:
		return true
	default:
		return false
	}
}

// Defines values for UserKind.
const (
	UserKindAgent UserKind = "agent"
	UserKindHuman UserKind = "human"
)

// Valid indicates whether the value is a known member of the UserKind enum.
func (e UserKind) Valid() bool {
	switch e {
	case UserKindAgent:
		return true
	case UserKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for VerifyCredentialInputKind.
const (
	VerifyCredentialInputKindSession VerifyCredentialInputKind = "session"
	VerifyCredentialInputKindToken   VerifyCredentialInputKind = "token"
)

// Valid indicates whether the value is a known member of the VerifyCredentialInputKind enum.
func (e VerifyCredentialInputKind) Valid() bool {
	switch e {
	case VerifyCredentialInputKindSession:
		return true
	case VerifyCredentialInputKindToken:
		return true
	default:
		return false
	}
}

// AddSshKeyInput defines model for AddSshKeyInput.
type AddSshKeyInput struct {
	// PublicKey Riga in formato `authorized_keys` (tipo, base64, commento facoltativo).
	//
	// Example: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAA... alice@laptop
	PublicKey string `json:"publicKey"`
	Title     string `json:"title"`
}

// ChangePasswordInput defines model for ChangePasswordInput.
type ChangePasswordInput struct {
	CurrentPassword *string `json:"currentPassword,omitempty"`
	NewPassword     *string `json:"newPassword,omitempty"`
}

// CheckPermissionInput defines model for CheckPermissionInput.
type CheckPermissionInput struct {
	ResourceId openapi_types.UUID `json:"resourceId"`

	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role   ResourceRole       `json:"role"`
	UserId openapi_types.UUID `json:"userId"`
}

// CheckPermissionResult defines model for CheckPermissionResult.
type CheckPermissionResult struct {
	Allowed       bool          `json:"allowed"`
	EffectiveRole *ResourceRole `json:"effectiveRole,omitempty"`
}

// CreateGrantInput defines model for CreateGrantInput.
type CreateGrantInput struct {
	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role        ResourceRole                `json:"role"`
	SubjectId   openapi_types.UUID          `json:"subjectId"`
	SubjectType CreateGrantInputSubjectType `json:"subjectType"`
}

// CreateGrantInputSubjectType defines model for CreateGrantInput.SubjectType.
type CreateGrantInputSubjectType string

// CreateTokenInput defines model for CreateTokenInput.
type CreateTokenInput struct {
	// ExpiresAt Obbligatoria: la scadenza deve essere nel futuro e non oltre il massimo configurato dall'installazione (default 365 giorni), altrimenti 422.
	ExpiresAt *time.Time   `json:"expiresAt,omitempty"`
	Name      string       `json:"name"`
	Scopes    []TokenScope `json:"scopes"`
}

// CreateUserInput defines model for CreateUserInput.
type CreateUserInput struct {
	DisplayName *string              `json:"displayName,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	IsAdmin     *bool                `json:"isAdmin,omitempty"`
	Kind        *CreateUserInputKind `json:"kind,omitempty"`

	// Password Assente per gli agenti (accedono solo con token) e per chi entra solo via OIDC.
	Password *string `json:"password,omitempty"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// CreateUserInputKind defines model for CreateUserInput.Kind.
type CreateUserInputKind string

// CreatedToken Il token appena creato; `token` compare solo in questa risposta.
type CreatedToken struct {
	CreatedAt time.Time  `json:"createdAt"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Hint Ultimi 4 caratteri del token, per riconoscerlo.
	Hint       string              `json:"hint"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	LastUsedAt *time.Time          `json:"lastUsedAt,omitempty"`
	Name       string              `json:"name"`
	Scopes     []TokenScope        `json:"scopes"`

	// Token Valore in chiaro, formato `gst_<casuale>`. Non viene salvato.
	Token string `json:"token"`
}

// CurrentSession defines model for CurrentSession.
type CurrentSession struct {
	// AuthMethod Come e' stato autenticato il chiamante.
	AuthMethod CurrentSessionAuthMethod `json:"authMethod"`
	ExpiresAt  *time.Time               `json:"expiresAt,omitempty"`

	// MustChangePassword Vero per l'amministratore creato al primo avvio finche' non cambia la password iniziale. Finche' e' vero ogni chiamata autenticata risponde 403 `password_change_required`, tranne `GET /auth/session`, `POST /auth/logout` e `PUT /users/{username}/password` (solo sulla propria utenza).
	MustChangePassword bool `json:"mustChangePassword"`

	// Scopes Solo per `authMethod` = `token`.
	Scopes *[]TokenScope `json:"scopes,omitempty"`

	// User Profilo utente. `email`, `isAdmin`, `isActive`, `createdAt` sono presenti solo per l'utente stesso e per gli amministratori.
	User User `json:"user"`
}

// CurrentSessionAuthMethod Come e' stato autenticato il chiamante.
type CurrentSessionAuthMethod string

// EffectivePermission defines model for EffectivePermission.
type EffectivePermission struct {
	ResourceId openapi_types.UUID `json:"resourceId"`

	// Role Ruolo effettivo; `null` = nessun accesso.
	Role *ResourceRole `json:"role"`
}

// Error Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Error struct {
	Error struct {
		// Code Codice stabile leggibile da macchina (es. `not_found`).
		//
		// Example: not_found
		Code string `json:"code"`

		// Details Dettagli opzionali specifici dell'errore.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Messaggio leggibile da persone, non contrattuale.
		Message string `json:"message"`
	} `json:"error"`
}

// Grant Ruolo su una risorsa generica (D15) per un utente o un team.
type Grant struct {
	CreatedAt  *time.Time          `json:"createdAt,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	ResourceId openapi_types.UUID  `json:"resourceId"`

	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role        ResourceRole       `json:"role"`
	SubjectId   openapi_types.UUID `json:"subjectId"`
	SubjectType GrantSubjectType   `json:"subjectType"`
}

// GrantSubjectType defines model for Grant.SubjectType.
type GrantSubjectType string

// GrantList defines model for GrantList.
type GrantList struct {
	Items   []Grant `json:"items"`
	Page    int     `json:"page"`
	PerPage int     `json:"perPage"`
	Total   int     `json:"total"`
}

// GrantResourceCreatorInput defines model for GrantResourceCreatorInput.
type GrantResourceCreatorInput struct {
	UserId openapi_types.UUID `json:"userId"`
}

// LoginInput defines model for LoginInput.
type LoginInput struct {
	Password *string `json:"password,omitempty"`

	// Username Username oppure email.
	Username string `json:"username"`
}

// Name Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type Name = string

// OidcProvider defines model for OidcProvider.
type OidcProvider struct {
	DisplayName string `json:"displayName"`

	// Slug Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Slug Name `json:"slug"`
}

// OidcProviderList defines model for OidcProviderList.
type OidcProviderList struct {
	Items []OidcProvider `json:"items"`
}

// Principal Chi ha presentato la credenziale.
type Principal struct {
	AuthMethod PrincipalAuthMethod `json:"authMethod"`

	// CredentialId Id della sessione o del token (per audit).
	CredentialId *openapi_types.UUID `json:"credentialId,omitempty"`
	ExpiresAt    *time.Time          `json:"expiresAt,omitempty"`
	IsAdmin      bool                `json:"isAdmin"`
	Kind         PrincipalKind       `json:"kind"`

	// MustChangePassword Vero per una sessione la cui password iniziale non e' ancora stata cambiata (vedi `CurrentSession.mustChangePassword`). `/internal/verify` risponde comunque `active` true: il gateway risponde 403 `password_change_required` a ogni rotta tranne `GET /auth/session`, `POST /auth/logout` e `PUT /users/{username}/password` sulla propria utenza. Assente equivale a falso.
	MustChangePassword *bool `json:"mustChangePassword,omitempty"`

	// Scopes Solo per i token; assenti per le sessioni.
	Scopes *[]TokenScope      `json:"scopes,omitempty"`
	UserId openapi_types.UUID `json:"userId"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// PrincipalAuthMethod defines model for Principal.AuthMethod.
type PrincipalAuthMethod string

// PrincipalKind defines model for Principal.Kind.
type PrincipalKind string

// ResourceRole Ruolo su una risorsa, in ordine crescente di potere.
type ResourceRole string

// SshKey defines model for SshKey.
type SshKey struct {
	CreatedAt   time.Time           `json:"createdAt"`
	Fingerprint string              `json:"fingerprint"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KeyType Example: ssh-ed25519
	KeyType    string     `json:"keyType"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	Title      string     `json:"title"`
}

// SshKeyList defines model for SshKeyList.
type SshKeyList struct {
	Items   []SshKey `json:"items"`
	Page    int      `json:"page"`
	PerPage int      `json:"perPage"`
	Total   int      `json:"total"`
}

// SshKeyLookup defines model for SshKeyLookup.
type SshKeyLookup struct {
	Key SshKey `json:"key"`

	// User Profilo utente. `email`, `isAdmin`, `isActive`, `createdAt` sono presenti solo per l'utente stesso e per gli amministratori.
	User User `json:"user"`
}

// Token Token personale, senza il valore (che non e' recuperabile).
type Token struct {
	CreatedAt time.Time  `json:"createdAt"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Hint Ultimi 4 caratteri del token, per riconoscerlo.
	Hint       string              `json:"hint"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	LastUsedAt *time.Time          `json:"lastUsedAt,omitempty"`
	Name       string              `json:"name"`
	Scopes     []TokenScope        `json:"scopes"`
}

// TokenList defines model for TokenList.
type TokenList struct {
	Items   []Token `json:"items"`
	Page    int     `json:"page"`
	PerPage int     `json:"perPage"`
	Total   int     `json:"total"`
}

// TokenScope Catalogo degli scope dei token personali (unico, condiviso da tutti i servizi). Le sessioni web non hanno scope: valgono i permessi dell'utente. `write:*` include `read:*` dello stesso ambito; `admin:org` include `write:org`.
type TokenScope string

// UpdateGrantInput defines model for UpdateGrantInput.
type UpdateGrantInput struct {
	// Role Ruolo su una risorsa, in ordine crescente di potere.
	Role ResourceRole `json:"role"`
}

// UpdateUserInput defines model for UpdateUserInput.
type UpdateUserInput struct {
	AvatarUrl   *string              `json:"avatarUrl,omitempty"`
	Bio         *string              `json:"bio,omitempty"`
	DisplayName *string              `json:"displayName,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`

	// IsActive Solo amministratori. Disattivare revoca le sessioni e i token.
	IsActive *bool `json:"isActive,omitempty"`

	// IsAdmin Solo amministratori.
	IsAdmin *bool `json:"isAdmin,omitempty"`
}

// User Profilo utente. `email`, `isAdmin`, `isActive`, `createdAt` sono presenti solo per l'utente stesso e per gli amministratori.
type User struct {
	AvatarUrl   *string              `json:"avatarUrl,omitempty"`
	Bio         *string              `json:"bio,omitempty"`
	CreatedAt   *time.Time           `json:"createdAt,omitempty"`
	DisplayName string               `json:"displayName"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Id          *openapi_types.UUID  `json:"id,omitempty"`
	IsActive    *bool                `json:"isActive,omitempty"`
	IsAdmin     *bool                `json:"isAdmin,omitempty"`
	Kind        UserKind             `json:"kind"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// UserKind defines model for User.Kind.
type UserKind string

// UserList defines model for UserList.
type UserList struct {
	Items   []User `json:"items"`
	Page    int    `json:"page"`
	PerPage int    `json:"perPage"`
	Total   int    `json:"total"`
}

// VerifyCredentialInput defines model for VerifyCredentialInput.
type VerifyCredentialInput struct {
	// Credential Valore grezzo della credenziale (cookie `gst_session` o token `gst_...`).
	Credential *string `json:"credential,omitempty"`

	// Kind Facoltativo, evita l'ambiguita' se il gateway la conosce.
	Kind *VerifyCredentialInputKind `json:"kind,omitempty"`
}

// VerifyCredentialInputKind Facoltativo, evita l'ambiguita' se il gateway la conosce.
type VerifyCredentialInputKind string

// VerifyCredentialResult defines model for VerifyCredentialResult.
type VerifyCredentialResult struct {
	Active bool `json:"active"`

	// CacheTtlSeconds Per quanto tempo il gateway puo' tenere in cache l'esito.
	CacheTtlSeconds *int `json:"cacheTtlSeconds,omitempty"`

	// Principal Chi ha presentato la credenziale.
	Principal *Principal `json:"principal,omitempty"`
}

// GrantIdParam defines model for GrantIdParam.
type GrantIdParam = openapi_types.UUID

// OidcProviderParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OidcProviderParam = Name

// OrgParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OrgParam = Name

// PageParam defines model for PageParam.
type PageParam = int

// PerPageParam defines model for PerPageParam.
type PerPageParam = int

// ResourceIdParam defines model for ResourceIdParam.
type ResourceIdParam = openapi_types.UUID

// SshKeyIdParam defines model for SshKeyIdParam.
type SshKeyIdParam = openapi_types.UUID

// TeamParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type TeamParam = Name

// TokenIdParam defines model for TokenIdParam.
type TokenIdParam = openapi_types.UUID

// UsernameParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type UsernameParam = Name

// BadRequest Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type BadRequest = Error

// Conflict Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Conflict = Error

// Forbidden Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Forbidden = Error

// NotFound Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type NotFound = Error

// TooManyRequests Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type TooManyRequests = Error

// Unauthorized Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Unauthorized = Error

// UnexpectedError Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type UnexpectedError = Error

// UnprocessableEntity Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`, `password_change_required`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type UnprocessableEntity = Error

// FinishOidcLoginParams defines parameters for FinishOidcLogin.
type FinishOidcLoginParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// StartOidcLoginParams defines parameters for StartOidcLogin.
type StartOidcLoginParams struct {
	RedirectTo *string `form:"redirectTo,omitempty" json:"redirectTo,omitempty"`
}

// ListResourceGrantsParams defines parameters for ListResourceGrants.
type ListResourceGrantsParams struct {
	Page    *PageParam    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListSshKeysParams defines parameters for ListSshKeys.
type ListSshKeysParams struct {
	Page    *PageParam    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	Page    *PageParam    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Q Prefisso di username o nome visualizzato.
	Q       *string       `form:"q,omitempty" json:"q,omitempty"`
	Page    *PageParam    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginInput

// CheckPermissionJSONRequestBody defines body for CheckPermission for application/json ContentType.
type CheckPermissionJSONRequestBody = CheckPermissionInput

// GrantResourceCreatorJSONRequestBody defines body for GrantResourceCreator for application/json ContentType.
type GrantResourceCreatorJSONRequestBody = GrantResourceCreatorInput

// VerifyCredentialJSONRequestBody defines body for VerifyCredential for application/json ContentType.
type VerifyCredentialJSONRequestBody = VerifyCredentialInput

// CreateResourceGrantJSONRequestBody defines body for CreateResourceGrant for application/json ContentType.
type CreateResourceGrantJSONRequestBody = CreateGrantInput

// UpdateResourceGrantJSONRequestBody defines body for UpdateResourceGrant for application/json ContentType.
type UpdateResourceGrantJSONRequestBody = UpdateGrantInput

// AddSshKeyJSONRequestBody defines body for AddSshKey for application/json ContentType.
type AddSshKeyJSONRequestBody = AddSshKeyInput

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenInput

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserInput

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserInput

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Accede con username e password
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Termina la sessione corrente
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// ListOidcProviders Provider OIDC abilitati
	// (GET /auth/oidc/providers)
	ListOidcProviders(w http.ResponseWriter, r *http.Request)
	// FinishOidcLogin Completa il login OIDC
	// (GET /auth/oidc/{provider}/callback)
	FinishOidcLogin(w http.ResponseWriter, r *http.Request, provider OidcProviderParam, params FinishOidcLoginParams)
	// StartOidcLogin Avvia il login OIDC
	// (GET /auth/oidc/{provider}/start)
	StartOidcLogin(w http.ResponseWriter, r *http.Request, provider OidcProviderParam, params StartOidcLoginParams)
	// GetCurrentSession Sessione corrente
	// (GET /auth/session)
	GetCurrentSession(w http.ResponseWriter, r *http.Request)
	// CheckPermission Verifica un permesso su una risorsa
	// (POST /internal/permissions/check)
	CheckPermission(w http.ResponseWriter, r *http.Request)
	// GrantResourceCreator Assegna il ruolo admin al creatore di una risorsa
	// (POST /internal/resources/{resourceId}/grants/creator)
	GrantResourceCreator(w http.ResponseWriter, r *http.Request, resourceId openapi_types.UUID)
	// LookupSshKey Risolve un utente dal fingerprint di una chiave SSH
	// (GET /internal/ssh-keys/{fingerprint})
	LookupSshKey(w http.ResponseWriter, r *http.Request, fingerprint string)
	// VerifyCredential Verifica una credenziale (per il gateway)
	// (POST /internal/verify)
	VerifyCredential(w http.ResponseWriter, r *http.Request)
	// ListResourceGrants Elenca i grant di una risorsa
	// (GET /resources/{resourceId}/grants)
	ListResourceGrants(w http.ResponseWriter, r *http.Request, resourceId ResourceIdParam, params ListResourceGrantsParams)
	// CreateResourceGrant Assegna un ruolo su una risorsa a un utente o a un team
	// (POST /resources/{resourceId}/grants)
	CreateResourceGrant(w http.ResponseWriter, r *http.Request, resourceId ResourceIdParam)
	// DeleteResourceGrant Revoca un grant
	// (DELETE /resources/{resourceId}/grants/{grantId})
	DeleteResourceGrant(w http.ResponseWriter, r *http.Request, resourceId ResourceIdParam, grantId GrantIdParam)
	// UpdateResourceGrant Cambia il ruolo di un grant
	// (PATCH /resources/{resourceId}/grants/{grantId})
	UpdateResourceGrant(w http.ResponseWriter, r *http.Request, resourceId ResourceIdParam, grantId GrantIdParam)
	// GetMyResourcePermission Permesso effettivo del chiamante su una risorsa
	// (GET /resources/{resourceId}/permissions)
	GetMyResourcePermission(w http.ResponseWriter, r *http.Request, resourceId ResourceIdParam)
	// ListSshKeys Elenca le chiavi SSH dell'utente corrente
	// (GET /user/ssh-keys)
	ListSshKeys(w http.ResponseWriter, r *http.Request, params ListSshKeysParams)
	// AddSshKey Aggiunge una chiave SSH
	// (POST /user/ssh-keys)
	AddSshKey(w http.ResponseWriter, r *http.Request)
	// DeleteSshKey Elimina una chiave SSH
	// (DELETE /user/ssh-keys/{keyId})
	DeleteSshKey(w http.ResponseWriter, r *http.Request, keyId SshKeyIdParam)
	// GetSshKey Legge una chiave SSH
	// (GET /user/ssh-keys/{keyId})
	GetSshKey(w http.ResponseWriter, r *http.Request, keyId SshKeyIdParam)
	// ListTokens Elenca i token personali dell'utente corrente
	// (GET /user/tokens)
	ListTokens(w http.ResponseWriter, r *http.Request, params ListTokensParams)
	// CreateToken Crea un token personale
	// (POST /user/tokens)
	CreateToken(w http.ResponseWriter, r *http.Request)
	// RevokeToken Revoca un token personale
	// (DELETE /user/tokens/{tokenId})
	RevokeToken(w http.ResponseWriter, r *http.Request, tokenId TokenIdParam)
	// ListUsers Elenca gli utenti
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// CreateUser Crea un utente
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// DeleteUser Elimina un utente
	// (DELETE /users/{username})
	DeleteUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// GetUser Legge il profilo di un utente
	// (GET /users/{username})
	GetUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// UpdateUser Aggiorna il profilo
	// (PATCH /users/{username})
	UpdateUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// ChangePassword Cambia la password
	// (PUT /users/{username}/password)
	ChangePassword(w http.ResponseWriter, r *http.Request, username UsernameParam)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOidcProviders operation middleware
func (siw *ServerInterfaceWrapper) ListOidcProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOidcProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FinishOidcLogin operation middleware
func (siw *ServerInterfaceWrapper) FinishOidcLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider OidcProviderParam

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params FinishOidcLoginParams

	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FinishOidcLogin(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartOidcLogin operation middleware
func (siw *ServerInterfaceWrapper) StartOidcLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider OidcProviderParam

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StartOidcLoginParams

	// ------------- Optional query parameter "redirectTo" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "redirectTo", r.URL.Query(), &params.RedirectTo, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "redirectTo"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirectTo", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartOidcLogin(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckPermission operation middleware
func (siw *ServerInterfaceWrapper) CheckPermission(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckPermission(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GrantResourceCreator operation middleware
func (siw *ServerInterfaceWrapper) GrantResourceCreator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", r.PathValue("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GrantResourceCreator(w, r, resourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupSshKey operation middleware
func (siw *ServerInterfaceWrapper) LookupSshKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "fingerprint" -------------
	var fingerprint string

	err = runtime.BindStyledParameterWithOptions("simple", "fingerprint", r.PathValue("fingerprint"), &fingerprint, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fingerprint", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupSshKey(w, r, fingerprint)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyCredential operation middleware
func (siw *ServerInterfaceWrapper) VerifyCredential(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyCredential(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListResourceGrants operation middleware
func (siw *ServerInterfaceWrapper) ListResourceGrants(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId ResourceIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", r.PathValue("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListResourceGrantsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListResourceGrants(w, r, resourceId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateResourceGrant operation middleware
func (siw *ServerInterfaceWrapper) CreateResourceGrant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId ResourceIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", r.PathValue("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateResourceGrant(w, r, resourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteResourceGrant operation middleware
func (siw *ServerInterfaceWrapper) DeleteResourceGrant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId ResourceIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", r.PathValue("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceId", Err: err})
		return
	}

	// ------------- Path parameter "grantId" -------------
	var grantId GrantIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "grantId", r.PathValue("grantId"), &grantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "grantId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteResourceGrant(w, r, resourceId, grantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateResourceGrant operation middleware
func (siw *ServerInterfaceWrapper) UpdateResourceGrant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId ResourceIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", r.PathValue("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceId", Err: err})
		return
	}

	// ------------- Path parameter "grantId" -------------
	var grantId GrantIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "grantId", r.PathValue("grantId"), &grantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "grantId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateResourceGrant(w, r, resourceId, grantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyResourcePermission operation middleware
func (siw *ServerInterfaceWrapper) GetMyResourcePermission(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId ResourceIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", r.PathValue("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyResourcePermission(w, r, resourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSshKeys operation middleware
func (siw *ServerInterfaceWrapper) ListSshKeys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSshKeysParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSshKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddSshKey operation middleware
func (siw *ServerInterfaceWrapper) AddSshKey(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddSshKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSshKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteSshKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId SshKeyIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", r.PathValue("keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSshKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSshKey operation middleware
func (siw *ServerInterfaceWrapper) GetSshKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId SshKeyIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", r.PathValue("keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSshKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTokens operation middleware
func (siw *ServerInterfaceWrapper) ListTokens(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokensParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTokens(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateToken operation middleware
func (siw *ServerInterfaceWrapper) CreateToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeToken operation middleware
func (siw *ServerInterfaceWrapper) RevokeToken(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tokenId" -------------
	var tokenId TokenIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "tokenId", r.PathValue("tokenId"), &tokenId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tokenId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeToken(w, r, tokenId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/session", wrapper.GetCurrentSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/oidc/providers", wrapper.ListOidcProviders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/oidc/{provider}/start", wrapper.StartOidcLogin)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/oidc/{provider}/callback", wrapper.FinishOidcLogin)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/users", wrapper.CreateUser)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/users/{username}", wrapper.DeleteUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/{username}", wrapper.GetUser)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/users/{username}", wrapper.UpdateUser)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/users/{username}/password", wrapper.ChangePassword)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/user/tokens", wrapper.ListTokens)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/user/tokens", wrapper.CreateToken)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/user/tokens/{tokenId}", wrapper.RevokeToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/user/ssh-keys", wrapper.ListSshKeys)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/user/ssh-keys", wrapper.AddSshKey)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/user/ssh-keys/{keyId}", wrapper.DeleteSshKey)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/user/ssh-keys/{keyId}", wrapper.GetSshKey)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/resources/{resourceId}/grants", wrapper.ListResourceGrants)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/resources/{resourceId}/grants", wrapper.CreateResourceGrant)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/resources/{resourceId}/grants/{grantId}", wrapper.DeleteResourceGrant)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/resources/{resourceId}/grants/{grantId}", wrapper.UpdateResourceGrant)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/resources/{resourceId}/permissions", wrapper.GetMyResourcePermission)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/internal/verify", wrapper.VerifyCredential)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/internal/permissions/check", wrapper.CheckPermission)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/internal/resources/{resourceId}/grants/creator", wrapper.GrantResourceCreator)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/internal/ssh-keys/{fingerprint}", wrapper.LookupSshKey)

	return m
}
