//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateUserInputKind.
const (
	CreateUserInputKindAgent CreateUserInputKind = "agent"
	CreateUserInputKindHuman CreateUserInputKind = "human"
)

// Valid indicates whether the value is a known member of the CreateUserInputKind enum.
func (e CreateUserInputKind) Valid() bool {
	switch e {
	case CreateUserInputKindAgent:
		return true
	case CreateUserInputKindHuman:
		return true
	default:
		return false
	}
}

// Defines values for CurrentSessionAuthMethod.
const (
	Oidc     CurrentSessionAuthMethod = "oidc"
	Password CurrentSessionAuthMethod = "password"
	Token    CurrentSessionAuthMethod = "token"
)

// Valid indicates whether the value is a known member of the CurrentSessionAuthMethod enum.
func (e CurrentSessionAuthMethod) Valid() bool {
	switch e {
	case Oidc:
		return true
	case Password:
		return true
	case Token:
		return true
	default:
		return false
	}
}

// Defines values for TokenScope.
const (
	AdminOrg      TokenScope = "admin:org"
	ReadOrg       TokenScope = "read:org"
	ReadResource  TokenScope = "read:resource"
	ReadUser      TokenScope = "read:user"
	WriteOrg      TokenScope = "write:org"
	WriteResource TokenScope = "write:resource"
	WriteUser     TokenScope = "write:user"
)

// Valid indicates whether the value is a known member of the TokenScope enum.
func (e TokenScope) Valid() bool {
	switch e {
	case AdminOrg:
		return true
	case ReadOrg:
		return true
	case ReadResource:
		return true
	case ReadUser:
		return true
	case WriteOrg:
		return true
	case WriteResource:
		return true
	case WriteUser:
		return true
	default:
		return false
	}
}

// Defines values for UserKind.
const (
	UserKindAgent UserKind = "agent"
	UserKindHuman UserKind = "human"
)

// Valid indicates whether the value is a known member of the UserKind enum.
func (e UserKind) Valid() bool {
	switch e {
	case UserKindAgent:
		return true
	case UserKindHuman:
		return true
	default:
		return false
	}
}

// ChangePasswordInput defines model for ChangePasswordInput.
type ChangePasswordInput struct {
	CurrentPassword *string `json:"currentPassword,omitempty"`
	NewPassword     *string `json:"newPassword,omitempty"`
}

// CreateUserInput defines model for CreateUserInput.
type CreateUserInput struct {
	DisplayName *string              `json:"displayName,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	IsAdmin     *bool                `json:"isAdmin,omitempty"`
	Kind        *CreateUserInputKind `json:"kind,omitempty"`

	// Password Assente per gli agenti (accedono solo con token) e per chi entra solo via OIDC.
	Password *string `json:"password,omitempty"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// CreateUserInputKind defines model for CreateUserInput.Kind.
type CreateUserInputKind string

// CurrentSession defines model for CurrentSession.
type CurrentSession struct {
	// AuthMethod Come e' stato autenticato il chiamante.
	AuthMethod CurrentSessionAuthMethod `json:"authMethod"`
	ExpiresAt  *time.Time               `json:"expiresAt,omitempty"`

	// Scopes Solo per `authMethod` = `token`.
	Scopes *[]TokenScope `json:"scopes,omitempty"`

	// User Profilo utente. `email`, `isAdmin`, `isActive`, `createdAt` sono presenti solo per l'utente stesso e per gli amministratori.
	User User `json:"user"`
}

// CurrentSessionAuthMethod Come e' stato autenticato il chiamante.
type CurrentSessionAuthMethod string

// Error Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Error struct {
	Error struct {
		// Code Codice stabile leggibile da macchina (es. `not_found`).
		//
		// Example: not_found
		Code string `json:"code"`

		// Details Dettagli opzionali specifici dell'errore.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Messaggio leggibile da persone, non contrattuale.
		Message string `json:"message"`
	} `json:"error"`
}

// LoginInput defines model for LoginInput.
type LoginInput struct {
	Password *string `json:"password,omitempty"`

	// Username Username oppure email.
	Username string `json:"username"`
}

// Name Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type Name = string

// OidcProvider defines model for OidcProvider.
type OidcProvider struct {
	DisplayName string `json:"displayName"`

	// Slug Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Slug Name `json:"slug"`
}

// OidcProviderList defines model for OidcProviderList.
type OidcProviderList struct {
	Items []OidcProvider `json:"items"`
}

// TokenScope Catalogo degli scope dei token personali (unico, condiviso da tutti i servizi). Le sessioni web non hanno scope: valgono i permessi dell'utente. `write:*` include `read:*` dello stesso ambito; `admin:org` include `write:org`.
type TokenScope string

// UpdateUserInput defines model for UpdateUserInput.
type UpdateUserInput struct {
	AvatarUrl   *string              `json:"avatarUrl,omitempty"`
	Bio         *string              `json:"bio,omitempty"`
	DisplayName *string              `json:"displayName,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`

	// IsActive Solo amministratori. Disattivare revoca le sessioni e i token.
	IsActive *bool `json:"isActive,omitempty"`

	// IsAdmin Solo amministratori.
	IsAdmin *bool `json:"isAdmin,omitempty"`
}

// User Profilo utente. `email`, `isAdmin`, `isActive`, `createdAt` sono presenti solo per l'utente stesso e per gli amministratori.
type User struct {
	AvatarUrl   *string              `json:"avatarUrl,omitempty"`
	Bio         *string              `json:"bio,omitempty"`
	CreatedAt   *time.Time           `json:"createdAt,omitempty"`
	DisplayName string               `json:"displayName"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Id          *openapi_types.UUID  `json:"id,omitempty"`
	IsActive    *bool                `json:"isActive,omitempty"`
	IsAdmin     *bool                `json:"isAdmin,omitempty"`
	Kind        UserKind             `json:"kind"`

	// Username Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
	//
	//
	// Example: alice
	Username Name `json:"username"`
}

// UserKind defines model for User.Kind.
type UserKind string

// UserList defines model for UserList.
type UserList struct {
	Items   []User `json:"items"`
	Page    int    `json:"page"`
	PerPage int    `json:"perPage"`
	Total   int    `json:"total"`
}

// GrantIdParam defines model for GrantIdParam.
type GrantIdParam = openapi_types.UUID

// OidcProviderParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OidcProviderParam = Name

// OrgParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type OrgParam = Name

// PageParam defines model for PageParam.
type PageParam = int

// PerPageParam defines model for PerPageParam.
type PerPageParam = int

// ResourceIdParam defines model for ResourceIdParam.
type ResourceIdParam = openapi_types.UUID

// SshKeyIdParam defines model for SshKeyIdParam.
type SshKeyIdParam = openapi_types.UUID

// TeamParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type TeamParam = Name

// TokenIdParam defines model for TokenIdParam.
type TokenIdParam = openapi_types.UUID

// UsernameParam Nome breve in minuscolo (username, organizzazione, team, provider): lettere minuscole, cifre e trattini, 1-39 caratteri, inizia e finisce con un carattere alfanumerico.
//
// Example: alice
type UsernameParam = Name

// BadRequest Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type BadRequest = Error

// Conflict Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Conflict = Error

// Forbidden Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Forbidden = Error

// NotFound Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type NotFound = Error

// TooManyRequests Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type TooManyRequests = Error

// Unauthorized Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type Unauthorized = Error

// UnexpectedError Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type UnexpectedError = Error

// UnprocessableEntity Formato unico degli errori per tutta l'API pubblica. Codici comuni per stato: 400 `bad_request`; 401 `unauthenticated`, `invalid_credentials`; 403 `forbidden`, `insufficient_scope`; 429 `too_many_attempts`; 404 `not_found`; 409 `conflict` e varianti specifiche (`already_exists`, `last_admin`, `last_owner`, `ssh_key_in_use`, `oidc_identity_unlinked`); 422 `validation_failed` (`details.fields`). Le risposte 401 non distinguono mai "utente inesistente" da "password errata".
type UnprocessableEntity = Error

// FinishOidcLoginParams defines parameters for FinishOidcLogin.
type FinishOidcLoginParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// StartOidcLoginParams defines parameters for StartOidcLogin.
type StartOidcLoginParams struct {
	RedirectTo *string `form:"redirectTo,omitempty" json:"redirectTo,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Q Prefisso di username o nome visualizzato.
	Q       *string       `form:"q,omitempty" json:"q,omitempty"`
	Page    *PageParam    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPageParam `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginInput

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserInput

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserInput

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Accede con username e password
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Termina la sessione corrente
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// ListOidcProviders Provider OIDC abilitati
	// (GET /auth/oidc/providers)
	ListOidcProviders(w http.ResponseWriter, r *http.Request)
	// FinishOidcLogin Completa il login OIDC
	// (GET /auth/oidc/{provider}/callback)
	FinishOidcLogin(w http.ResponseWriter, r *http.Request, provider OidcProviderParam, params FinishOidcLoginParams)
	// StartOidcLogin Avvia il login OIDC
	// (GET /auth/oidc/{provider}/start)
	StartOidcLogin(w http.ResponseWriter, r *http.Request, provider OidcProviderParam, params StartOidcLoginParams)
	// GetCurrentSession Sessione corrente
	// (GET /auth/session)
	GetCurrentSession(w http.ResponseWriter, r *http.Request)
	// ListUsers Elenca gli utenti
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// CreateUser Crea un utente
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// DeleteUser Elimina un utente
	// (DELETE /users/{username})
	DeleteUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// GetUser Legge il profilo di un utente
	// (GET /users/{username})
	GetUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// UpdateUser Aggiorna il profilo
	// (PATCH /users/{username})
	UpdateUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// ChangePassword Cambia la password
	// (PUT /users/{username}/password)
	ChangePassword(w http.ResponseWriter, r *http.Request, username UsernameParam)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOidcProviders operation middleware
func (siw *ServerInterfaceWrapper) ListOidcProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOidcProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FinishOidcLogin operation middleware
func (siw *ServerInterfaceWrapper) FinishOidcLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider OidcProviderParam

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params FinishOidcLoginParams

	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FinishOidcLogin(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartOidcLogin operation middleware
func (siw *ServerInterfaceWrapper) StartOidcLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider OidcProviderParam

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StartOidcLoginParams

	// ------------- Optional query parameter "redirectTo" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "redirectTo", r.URL.Query(), &params.RedirectTo, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "redirectTo"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirectTo", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartOidcLogin(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "perPage", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "perPage"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/session", wrapper.GetCurrentSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/oidc/providers", wrapper.ListOidcProviders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/oidc/{provider}/start", wrapper.StartOidcLogin)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/oidc/{provider}/callback", wrapper.FinishOidcLogin)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/users", wrapper.CreateUser)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/users/{username}", wrapper.DeleteUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/{username}", wrapper.GetUser)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/users/{username}", wrapper.UpdateUser)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/users/{username}/password", wrapper.ChangePassword)

	return m
}
